// Every page listed on the safelite.com site map, in the same order. Top-level
// entries are shown in bold; nested lists go up to four levels deep.
export type SiteMapLink = { label: string; href: string; children?: SiteMapLink[] };

export const SITE_MAP: SiteMapLink[] = [
  { label: "Home", href: "/" },
  { label: "My appointment", href: "/my-appointment" },
  { label: "Site map", href: "/site-map" },
  { label: "About Us", href: "/about-safelite", children: [
    { label: "Safelite Foundation", href: "/about-safelite/safelite-autoglass-foundation" },
    { label: "Our Leaders", href: "/about-safelite/our-leaders" },
    { label: "Our Partnerships", href: "/about-safelite/safelite-partnerships" },
    { label: "Safelite Group Companies", href: "/about-safelite/safelite-autoglass-companies" },
  ] },
  { label: "Careers", href: "/careers", children: [
    { label: "Auto Glass Technician Jobs", href: "/careers/auto-glass-technician-jobs" },
    { label: "Customer Service Jobs", href: "/careers/customer-service-representative-jobs" },
  ] },
  { label: "Misc Content", href: "/misc-content", children: [
    { label: "Terms of service", href: "/terms-of-service" },
    { label: "Cancellation policy", href: "/cancellation-refund-policy" },
    { label: "Notice at collection", href: "/ccpa-privacy-policy" },
    { label: "Safelite Agent Express", href: "/agent-express" },
    { label: "Glasspro", href: "/glasspro" },
    { label: "Tesla", href: "/tesla" },
    { label: "Mail Unsubscribe", href: "/mail-unsubscribe" },
    { label: "Biometric Processing Policy", href: "/biometric-policy" },
    { label: "Electronic-communication-disclosure-consent", href: "/electronic-communication-disclosure-consent" },
  ] },
  { label: "Locations", href: "/stores" },
  { label: "Contact us", href: "/contact-us" },
  { label: "Products", href: "/products/safelite-glass-cleaner" },
  { label: "Vehicles", href: "/vehicle-glass-repair", children: [
    { label: "Acura", href: "/vehicle-glass-repair/acura-windshield-replacements", children: [
      { label: "Acura ADAS", href: "/vehicle-glass-repair/acura-adas-recalibration" },
      { label: "Acura ADX", href: "/vehicle-glass-repair/acura-adx-windshields" },
      { label: "Acura ILX", href: "/vehicle-glass-repair/acura-ilx-windshields" },
      { label: "Acura Integra", href: "/vehicle-glass-repair/acura-integra-windshields" },
      { label: "Acura MDX", href: "/vehicle-glass-repair/acura-mdx-windshields" },
      { label: "Acura RDX", href: "/vehicle-glass-repair/acura-rdx-windshields" },
      { label: "Acura RSX", href: "/vehicle-glass-repair/acura-rsx-windshields" },
      { label: "Acura TL", href: "/vehicle-glass-repair/acura-tl-windshields" },
      { label: "Acura TLX", href: "/vehicle-glass-repair/acura-tlx" },
      { label: "Acura ZDX", href: "/vehicle-glass-repair/acura-zdx-windshields" },
    ] },
    { label: "Alfa Romeo", href: "/vehicle-glass-repair/alfa-romeo-windshield-replacements", children: [
      { label: "Alfa Romeo Giulia", href: "/vehicle-glass-repair/alfa-romeo-giulia-windshields" },
      { label: "Alfa Romeo Stelvio", href: "/vehicle-glass-repair/alfa-romeo-stelvio-windshields" },
      { label: "Alfa Romeo Tonale", href: "/vehicle-glass-repair/alfa-romeo-tonale-windshield-replacement" },
    ] },
    { label: "Audi", href: "/vehicle-glass-repair/audi-windshield-replacements", children: [
      { label: "Audi A3", href: "/vehicle-glass-repair/audi-a3-windshields" },
      { label: "Audi A4", href: "/vehicle-glass-repair/audi-a4-windshields" },
      { label: "Audi A4 Allroad", href: "/vehicle-glass-repair/audi-a4-allroad-windshields" },
      { label: "Audi A5", href: "/vehicle-glass-repair/audi-a5-windshields" },
      { label: "Audi A6", href: "/vehicle-glass-repair/audi-a6-windshields" },
      { label: "Audi A7", href: "/vehicle-glass-repair/audi-a7-windshields" },
      { label: "Audi A8L", href: "/vehicle-glass-repair/audi-a8l-windshields" },
      { label: "Audi ADAS Sensing", href: "/vehicle-glass-repair/audi-sensing-adas-recalibration" },
      { label: "Audi E-Tron", href: "/vehicle-glass-repair/audi-etron-windshields" },
      { label: "Audi Q3", href: "/vehicle-glass-repair/audi-q3-windshields" },
      { label: "Audi Q5", href: "/vehicle-glass-repair/audi-q5-windshields" },
      { label: "Audi Q7", href: "/vehicle-glass-repair/audi-q7-windshields" },
      { label: "Audi Q8", href: "/vehicle-glass-repair/audi-q8-windshields" },
      { label: "Audi R8", href: "/vehicle-glass-repair/audi-r8" },
      { label: "Audi RS 7", href: "/vehicle-glass-repair/audi-rs7-windshield-replacement" },
      { label: "Audi S3", href: "/vehicle-glass-repair/audi-s3-windshields" },
      { label: "Audi S4", href: "/vehicle-glass-repair/audi-s4-windshields" },
      { label: "Audi S5", href: "/vehicle-glass-repair/audi-s5-windshields" },
      { label: "Audi S6", href: "/vehicle-glass-repair/audi-s6-windshields" },
      { label: "Audi S7", href: "/vehicle-glass-repair/audi-s7-windshields" },
      { label: "Audi S8", href: "/vehicle-glass-repair/audi-s8-windshields" },
      { label: "Audi SQ5", href: "/vehicle-glass-repair/audi-sq5-windshields" },
      { label: "Audi TT", href: "/vehicle-glass-repair/audi-tt-windshields" },
    ] },
    { label: "BMW", href: "/vehicle-glass-repair/bmw-windshield-replacements", children: [
      { label: "BMW 3 Series", href: "/vehicle-glass-repair/bmw-3-series-windshields" },
      { label: "BMW 4 Series", href: "/vehicle-glass-repair/bmw-4-series-windshield-replacement" },
      { label: "BMW 5 Series", href: "/vehicle-glass-repair/bmw-5-series-windshields" },
      { label: "BMW 530e", href: "/vehicle-glass-repair/bmw-530e-windshield-replacement" },
      { label: "BMW 530i", href: "/vehicle-glass-repair/bmw-530i-windshield-replacement" },
      { label: "BMW 540i", href: "/vehicle-glass-repair/bmw-540i-windshield-replacement" },
      { label: "BMW 7 Series", href: "/vehicle-glass-repair/bmw-7-series-windshield-replacement" },
      { label: "BMW ADAS Sensing", href: "/vehicle-glass-repair/bmw-adas-sensing-adas-recalibration" },
      { label: "BMW M2", href: "/vehicle-glass-repair/bmw-m2" },
      { label: "BMW M3", href: "/vehicle-glass-repair/bmw-m3-windshields" },
      { label: "BMW M4", href: "/vehicle-glass-repair/bmw-m4" },
      { label: "BMW M5", href: "/vehicle-glass-repair/bmw-m5" },
      { label: "BMW M550i", href: "/vehicle-glass-repair/bmw-m550i-windshield-replacement" },
      { label: "BMW X1", href: "/vehicle-glass-repair/bmw-x1-windshield-replacement" },
      { label: "BMW X2", href: "/vehicle-glass-repair/bmw-x2-windshield-replacement" },
      { label: "BMW X3", href: "/vehicle-glass-repair/bmw-x3-windshields" },
      { label: "BMW X4", href: "/vehicle-glass-repair/bmw-x4-windshields" },
      { label: "BMW X5", href: "/vehicle-glass-repair/bmw-x5-windshields" },
      { label: "BMW X6", href: "/vehicle-glass-repair/bmw-x6-windshields" },
      { label: "BMW X7", href: "/vehicle-glass-repair/bmw-x7-windshields" },
      { label: "BMW XM", href: "/vehicle-glass-repair/bmw-xm-windshields" },
      { label: "BMW Z4", href: "/vehicle-glass-repair/bmw-z4" },
    ] },
    { label: "Buick", href: "/vehicle-glass-repair/buick-windshield-replacements", children: [
      { label: "Buick ADAS", href: "/vehicle-glass-repair/buick-adas-recalibration" },
      { label: "Buick Enclave", href: "/vehicle-glass-repair/buick-enclave-windshield-replacements" },
      { label: "Buick Encore", href: "/vehicle-glass-repair/buick-encore-windshield-replacements" },
      { label: "Buick Envista", href: "/vehicle-glass-repair/buick-envista-windshield-replacements" },
      { label: "Buick Envision", href: "/vehicle-glass-repair/buick-envision-windshield-replacements" },
      { label: "Buick Regal", href: "/vehicle-glass-repair/buick-regal-windshield-replacements" },
    ] },
    { label: "Cadillac", href: "/vehicle-glass-repair/cadillac", children: [
      { label: "Cadillac ATS", href: "/vehicle-glass-repair/cadillac-ats-windshield-replacements" },
      { label: "Cadillac CELESTIQ", href: "/vehicle-glass-repair/cadillac-celestiq-windshield-replacement" },
      { label: "Cadillac CT4", href: "/vehicle-glass-repair/cadillac-ct4-windshield-replacement" },
      { label: "Cadillac CT5", href: "/vehicle-glass-repair/cadillac-ct5-windshield-replacement" },
      { label: "Cadillac CT6", href: "/vehicle-glass-repair/cadillac-ct6-windshields" },
      { label: "Cadillac Escalade", href: "/vehicle-glass-repair/cadillac-escalade-windshields" },
      { label: "Cadillac Escalade IQ", href: "/vehicle-glass-repair/cadillac-escalade-iq-windshields" },
      { label: "Cadillac Lyriq", href: "/vehicle-glass-repair/cadillac-lyriq-windshield-replacement" },
      { label: "Cadillac Lyriq-V", href: "/vehicle-glass-repair/cadillac-lyriq-v-windshields" },
      { label: "Cadillac OPTIQ", href: "/vehicle-glass-repair/cadillac-optiq" },
      { label: "Cadillac Super Cruise ADAS", href: "/vehicle-glass-repair/cadillac-adas-recalibration" },
      { label: "Cadillac VISTIQ", href: "/vehicle-glass-repair/cadillac-vistiq-windshield-replacement" },
      { label: "Cadillac XT4", href: "/vehicle-glass-repair/cadillac-xt4" },
      { label: "Cadillac XT5", href: "/vehicle-glass-repair/cadillac-xt5-windshield-replacement" },
      { label: "Cadillac XT6", href: "/vehicle-glass-repair/cadillac-xt6-windshield-replacement" },
    ] },
    { label: "Chevrolet", href: "/vehicle-glass-repair/chevrolet-windshield-replacements", children: [
      { label: "Chevrolet Blazer", href: "/vehicle-glass-repair/chevrolet-blazer-windshield-replacement" },
      { label: "Chevrolet Bolt", href: "/vehicle-glass-repair/chevrolet-bolt-windshield-replacement" },
      { label: "Chevrolet Bolt EV", href: "/vehicle-glass-repair/chevrolet-bolt-ev-windshields" },
      { label: "Chevrolet Camaro", href: "/vehicle-glass-repair/chevrolet-camaro-windshield-replacement" },
      { label: "Chevrolet Colorado", href: "/vehicle-glass-repair/chevy-colorado-windshield-replacements" },
      { label: "Chevrolet Corvette", href: "/vehicle-glass-repair/chevrolet-corvette-windshield-replacement" },
      { label: "Chevrolet Cruze", href: "/vehicle-glass-repair/chevrolet-cruze", children: [
        { label: "2014 Chevy Cruze", href: "/vehicle-glass-repair/2014-chevrolet-cruze-windshields" },
        { label: "2015 Chevy Cruze", href: "/vehicle-glass-repair/2015-chevy-cruze-windshields" },
      ] },
      { label: "Chevrolet Equinox", href: "/vehicle-glass-repair/chevy-equinox-windshield-replacements", children: [
        { label: "2012 Chevy Equinox", href: "/vehicle-glass-repair/2012-chevy-equinox-windshields" },
      ] },
      { label: "Chevrolet Equinox EV", href: "/vehicle-glass-repair/chevy-equinox-ev-windshield-replacements" },
      { label: "Chevrolet Express", href: "/vehicle-glass-repair/chevrolet-express-windshield-replacement" },
      { label: "Chevrolet Impala", href: "/vehicle-glass-repair/chevrolet-impala", children: [
        { label: "2008 Chevy Impala", href: "/vehicle-glass-repair/2008-chevrolet-impala-windshields" },
      ] },
      { label: "Chevrolet Malibu", href: "/vehicle-glass-repair/chevrolet-malibu" },
      { label: "Chevrolet Safety Assist ADAS Page", href: "/vehicle-glass-repair/chevrolet-adas-recalibration" },
      { label: "Chevrolet Silverado", href: "/vehicle-glass-repair/chevrolet-silverado", children: [
        { label: "2014 Chevy Silverado", href: "/vehicle-glass-repair/2014-chevy-silverado-windshields" },
      ] },
      { label: "Chevrolet Silverado EV Trail Boss", href: "/vehicle-glass-repair/chevrolet-silverado-ev-trail-boss-windshields" },
      { label: "Chevrolet Suburban", href: "/vehicle-glass-repair/chevrolet-suburban-windshield-replacement" },
      { label: "Chevrolet Tahoe", href: "/vehicle-glass-repair/chevrolet-tahoe", children: [
        { label: "2013 Chevy Tahoe", href: "/vehicle-glass-repair/2013-chevy-tahoe-windshields" },
      ] },
      { label: "Chevrolet Trailblazer", href: "/vehicle-glass-repair/chevrolet-trailblazer-windshield-replacement" },
      { label: "Chevrolet Trax", href: "/vehicle-glass-repair/chevrolet-trax" },
      { label: "Chevrolet Traverse", href: "/vehicle-glass-repair/chevrolet-traverse-windshield-replacements" },
      { label: "Chevrolet Volt", href: "/vehicle-glass-repair/chevrolet-volt-windshield-replacement" },
    ] },
    { label: "Chrysler", href: "/vehicle-glass-repair/chrysler-windshield-repair-replacement", children: [
      { label: "Chrysler 200", href: "/vehicle-glass-repair/chrysler-200-windshield-replacements", children: [
        { label: "2015 Chrysler 200", href: "/vehicle-glass-repair/2015-chrysler-200-windshields" },
      ] },
      { label: "Chrysler 300", href: "/vehicle-glass-repair/chrysler-300-windshield-replacements" },
      { label: "Chrysler Airflow", href: "/vehicle-glass-repair/chrysler-airflow-windshield-replacement" },
      { label: "Chrysler Pacifica", href: "/vehicle-glass-repair/chrysler-pacifica-windshield-replacements" },
      { label: "Chrysler Pinnacle", href: "/vehicle-glass-repair/chrysler-pinnacle-windshield-replacement" },
      { label: "Chrysler Sebring", href: "/vehicle-glass-repair/chrysler-sebring-windshield-replacement" },
      { label: "Chrysler Voyager", href: "/vehicle-glass-repair/chrysler-voyager" },
    ] },
    { label: "Dodge", href: "/vehicle-glass-repair/dodge-windshield-replacements", children: [
      { label: "Dodge Challenger", href: "/vehicle-glass-repair/dodge-challenger-windshields" },
      { label: "Dodge Charger", href: "/vehicle-glass-repair/dodge-charger-windshields" },
      { label: "Dodge Dart", href: "/vehicle-glass-repair/dodge-dart-windshields" },
      { label: "Dodge Durango", href: "/vehicle-glass-repair/dodge-durango-windshields" },
      { label: "Dodge Grand Caravan", href: "/vehicle-glass-repair/dodge-durango-grand-caravan-windshields" },
      { label: "Dodge Hornet", href: "/vehicle-glass-repair/dodge-hornet-windshield-replacement" },
      { label: "Dodge Journey", href: "/vehicle-glass-repair/dodge-journey-windshield-replacement" },
      { label: "Dodge Ram", href: "/vehicle-glass-repair/dodge-ram-windshields" },
    ] },
    { label: "Fiat", href: "/vehicle-glass-repair/fiat-windshield-replacements", children: [
      { label: "Fiat 124", href: "/vehicle-glass-repair/fiat-124-spider-windshields" },
      { label: "Fiat 500e", href: "/vehicle-glass-repair/fiat-500e" },
      { label: "Fiat 500x", href: "/vehicle-glass-repair/fiat-500x" },
    ] },
    { label: "Fisker", href: "/vehicle-glass-repair/fisker-windshield-replacements", children: [
      { label: "Fisker Ocean", href: "/vehicle-glass-repair/fisker-ocean-windshields" },
    ] },
    { label: "Ford", href: "/vehicle-glass-repair/ford-windshield-replacements", children: [
      { label: "Ford Bronco", href: "/vehicle-glass-repair/ford-bronco-windshield-replacement" },
      { label: "Ford Bronco Sport", href: "/vehicle-glass-repair/ford-bronco-sport-windshield-replacement" },
      { label: "Ford CoPilot360", href: "/vehicle-glass-repair/ford-copilot-360-adas-recalibration" },
      { label: "Ford Edge", href: "/vehicle-glass-repair/ford-edge-windshields" },
      { label: "Ford Escape", href: "/vehicle-glass-repair/ford-escape-windshields", children: [
        { label: "2008 Ford Escape", href: "/vehicle-glass-repair/2008-ford-escape-windshield" },
        { label: "2010 Ford Escape", href: "/vehicle-glass-repair/2010-ford-escape-windshields" },
        { label: "2011 Ford Escape", href: "/vehicle-glass-repair/2011-ford-escape-windshields" },
        { label: "2013 Ford Escape", href: "/vehicle-glass-repair/2013-ford-escape-windshields" },
        { label: "2017 Ford Escape", href: "/vehicle-glass-repair/2017-ford-escape-windshields" },
      ] },
      { label: "Ford Expedition", href: "/vehicle-glass-repair/ford-expedition-windshield-replacement" },
      { label: "Ford Expedition Max", href: "/vehicle-glass-repair/ford-expedition-max-windshield-replacement" },
      { label: "Ford Explorer", href: "/vehicle-glass-repair/ford-explorer-windshields" },
      { label: "Ford F-150", href: "/vehicle-glass-repair/ford-f-150-windshields", children: [
        { label: "2013 Ford F-150", href: "/vehicle-glass-repair/2013-ford-f-150-windshields" },
      ] },
      { label: "Ford F-250", href: "/vehicle-glass-repair/ford-f-250-windshields" },
      { label: "Ford F-350", href: "/vehicle-glass-repair/ford-f-350-windshields" },
      { label: "Ford F-550", href: "/vehicle-glass-repair/ford-f-550-windshields" },
      { label: "Ford Fiesta", href: "/vehicle-glass-repair/ford-fiesta-windshield-replacement" },
      { label: "Ford Flex", href: "/vehicle-glass-repair/ford-flex-windshield-replacement" },
      { label: "Ford Focus", href: "/vehicle-glass-repair/ford-focus-windshields", children: [
        { label: "2014 Ford Focus", href: "/vehicle-glass-repair/2014-ford-focus-windshields" },
      ] },
      { label: "Ford Fusion", href: "/vehicle-glass-repair/ford-fusion-windshields", children: [
        { label: "2014 Ford Fusion", href: "/vehicle-glass-repair/2014-ford-fusion-windshields" },
        { label: "2015 Ford Fusion", href: "/vehicle-glass-repair/2015-ford-fusion-windshields" },
      ] },
      { label: "Ford Maverick", href: "/vehicle-glass-repair/ford-maverick-windshield-replacement" },
      { label: "Ford Mustang", href: "/vehicle-glass-repair/ford-mustang-windshields" },
      { label: "Ford Mustang Mach-E", href: "/vehicle-glass-repair/ford-mustang-mach-e-windshields" },
      { label: "Ford Ranger", href: "/vehicle-glass-repair/ford-ranger-windshields" },
      { label: "Ford Taurus", href: "/vehicle-glass-repair/ford-taurus-windshield-replacement" },
      { label: "Ford Transit", href: "/vehicle-glass-repair/ford-transit-windshield-replacement" },
    ] },
    { label: "Genesis", href: "/vehicle-glass-repair/genesis-windshield-replacements", children: [
      { label: "Genesis G70", href: "/vehicle-glass-repair/genesis-g70-windshields" },
      { label: "Genesis G80", href: "/vehicle-glass-repair/genesis-g80-windshields" },
      { label: "Genesis G90", href: "/vehicle-glass-repair/genesis-g90-windshields" },
      { label: "Genesis GV60", href: "/vehicle-glass-repair/genesis-gv60-windshields" },
      { label: "Genesis GV70", href: "/vehicle-glass-repair/genesis-gv70-windshields" },
      { label: "Genesis GV80", href: "/vehicle-glass-repair/genesis-gv80-windshields" },
    ] },
    { label: "GMC", href: "/vehicle-glass-repair/gmc-windshield-replacements", children: [
      { label: "GMC ADAS", href: "/vehicle-glass-repair/gmc-adas-recalibration" },
      { label: "GMC Acadia", href: "/vehicle-glass-repair/gmc-acadia-windshield-replacement" },
      { label: "GMC Canyon", href: "/vehicle-glass-repair/gmc-canyon-windshield-replacement" },
      { label: "GMC Savana", href: "/vehicle-glass-repair/gmc-savana-windshield-replacement" },
      { label: "GMC Sierra", href: "/vehicle-glass-repair/gmc-sierra-windshield-replacement" },
      { label: "GMC Sierra EV", href: "/vehicle-glass-repair/gmc-sierra-ev-windshield-replacement" },
      { label: "GMC Terrain", href: "/vehicle-glass-repair/gmc-terrain-windshield-replacement" },
      { label: "GMC Yukon", href: "/vehicle-glass-repair/gmc-yukon-windshield-replacement" },
      { label: "GMC Yukon XL", href: "/vehicle-glass-repair/gmc-yukon-xl-windshield-replacement" },
    ] },
    { label: "Honda", href: "/vehicle-glass-repair/honda-windshield-replacements", children: [
      { label: "Honda Accord", href: "/vehicle-glass-repair/honda-accord-windshields", children: [
        { label: "2003 Honda Accord", href: "/vehicle-glass-repair/2003-honda-accord-windshields" },
        { label: "2004 Honda Accord", href: "/vehicle-glass-repair/2004-honda-accord-windshields" },
        { label: "2006 Honda Accord", href: "/vehicle-glass-repair/2006-honda-accord-windshields" },
        { label: "2010 Honda Accord", href: "/vehicle-glass-repair/2010-honda-accord-windshields" },
        { label: "2018 Honda Accord", href: "/vehicle-glass-repair/2018-honda-accord-windshields" },
      ] },
      { label: "Honda Civic", href: "/vehicle-glass-repair/honda-civic-windshields", children: [
        { label: "2016 Honda Civic", href: "/vehicle-glass-repair/2016-honda-civic-windshields" },
        { label: "2017 Honda Civic", href: "/vehicle-glass-repair/2017-honda-civic-windshields" },
      ] },
      { label: "Honda Clarity", href: "/vehicle-glass-repair/honda-clarity-windshield-replacement" },
      { label: "Honda CR-V", href: "/vehicle-glass-repair/honda-cr-v-windshields", children: [
        { label: "2013 Honda CR-V", href: "/vehicle-glass-repair/2013-honda-cr-v-windshields" },
        { label: "2015 Honda CR-V", href: "/vehicle-glass-repair/2015-honda-crv-windshields" },
      ] },
      { label: "Honda Element", href: "/vehicle-glass-repair/honda-element-windshields" },
      { label: "Honda Fit", href: "/vehicle-glass-repair/honda-fit-windshield-replacement" },
      { label: "Honda HRV", href: "/vehicle-glass-repair/honda-hr-v-windshields" },
      { label: "Honda Insight", href: "/vehicle-glass-repair/honda-insight-windshield-replacement" },
      { label: "Honda Odyssey", href: "/vehicle-glass-repair/honda-odyssey-windshields", children: [
        { label: "2012 Honda Odyssey", href: "/vehicle-glass-repair/2012-honda-odyssey-windshields" },
      ] },
      { label: "Honda Passport", href: "/vehicle-glass-repair/honda-passport-windshield-replacement" },
      { label: "Honda Pilot", href: "/vehicle-glass-repair/honda-pilot-windshields", children: [
        { label: "2012 Honda Pilot", href: "/vehicle-glass-repair/2012-honda-pilot-windshields" },
        { label: "2013 Honda Pilot", href: "/vehicle-glass-repair/2013-honda-pilot-windshields" },
        { label: "2016 Honda Pilot", href: "/vehicle-glass-repair/2016-honda-pilot-windshields" },
      ] },
      { label: "Honda Pilot TrailSport", href: "/vehicle-glass-repair/honda-trailsport-windshield-replacement" },
      { label: "Honda Prelude", href: "/vehicle-glass-repair/honda-prelude-windshields" },
      { label: "Honda Prologue", href: "/vehicle-glass-repair/honda-prologue-windshield-replacement" },
      { label: "Honda Ridgeline", href: "/vehicle-glass-repair/honda-ridgeline-windshield-replacement" },
      { label: "Honda Sensing", href: "/vehicle-glass-repair/honda-safety-sense-adas-recalibration" },
    ] },
    { label: "Hummer", href: "/vehicle-glass-repair/hummer-windshield-replacements", children: [
      { label: "Hummer EV 3X", href: "/vehicle-glass-repair/hummer-ev-3x" },
      { label: "Hummer EV Pickup", href: "/vehicle-glass-repair/hummer-ev-pickup-windshields" },
      { label: "Hummer H3", href: "/vehicle-glass-repair/hummer-h3" },
    ] },
    { label: "Hyundai", href: "/vehicle-glass-repair/hyundai-windshield-replacements", children: [
      { label: "Hyundai Accent", href: "/vehicle-glass-repair/hyundai-accent-windshield-replacement" },
      { label: "Hyundai ADAS", href: "/vehicle-glass-repair/hyundai-adas-recalibration" },
      { label: "Hyundai Elantra", href: "/vehicle-glass-repair/hyundai-elantra-windshields", children: [
        { label: "2013 Hyundai Elantra", href: "/vehicle-glass-repair/2013-hyundai-elantra-windshields" },
      ] },
      { label: "Hyundai Elantra N", href: "/vehicle-glass-repair/hyundai-elantra-n-windshields" },
      { label: "Hyundai Genesis", href: "/vehicle-glass-repair/hyundai-genesis-windshields" },
      { label: "Hyundai IONIQ 5", href: "/vehicle-glass-repair/hyundai-ioniq-5" },
      { label: "Hyundai IONIQ 6", href: "/vehicle-glass-repair/hyundai-ioniq-6-windshield-replacement" },
      { label: "Hyundai IONIQ 9", href: "/vehicle-glass-repair/hyundai-ioniq-9-windshields" },
      { label: "Hyundai Kona", href: "/vehicle-glass-repair/hyundai-kona-windshield-replacement" },
      { label: "Hyundai NEXO", href: "/vehicle-glass-repair/hyundai-nexo" },
      { label: "Hyundai Palisade", href: "/vehicle-glass-repair/hyundai-palisade-windshield-replacement" },
      { label: "Hyundai Santa Cruz", href: "/vehicle-glass-repair/hyundai-santa-cruz-windshield-replacement" },
      { label: "Hyundai Santa Fe", href: "/vehicle-glass-repair/hyundai-santa-fe-windshields" },
      { label: "Hyundai Sonata", href: "/vehicle-glass-repair/hyundai-sonata-windshields" },
      { label: "Hyundai Tucson", href: "/vehicle-glass-repair/hyundai-tucson-windshields" },
      { label: "Hyundai Venue", href: "/vehicle-glass-repair/hyundai-venue-windshield-replacement" },
    ] },
    { label: "INEOS Grenadier", href: "/vehicle-glass-repair/ineos-grenadier-windshield-replacements" },
    { label: "Infiniti", href: "/vehicle-glass-repair/infiniti-windshield-replacements", children: [
      { label: "Infiniti G35", href: "/vehicle-glass-repair/infiniti-g35-windshield-replacement" },
      { label: "Infiniti G37", href: "/vehicle-glass-repair/infiniti-g37-windshield-replacement" },
      { label: "Infiniti ProPILOT Assist ADAS", href: "/vehicle-glass-repair/infiniti-adas-recalibration" },
      { label: "Infiniti Q40", href: "/vehicle-glass-repair/infiniti-q40-windshield-replacement" },
      { label: "Infiniti Q50", href: "/vehicle-glass-repair/infiniti-q50-windshield-replacement" },
      { label: "Infiniti Q60", href: "/vehicle-glass-repair/infiniti-q60-windshield-replacement" },
      { label: "Infiniti Q70", href: "/vehicle-glass-repair/infiniti-q70-windshield-replacement" },
      { label: "Infiniti QX50", href: "/vehicle-glass-repair/infiniti-qx50-windshields" },
      { label: "Infiniti QX60", href: "/vehicle-glass-repair/infiniti-qx60-windshields" },
      { label: "Infiniti QX80", href: "/vehicle-glass-repair/infiniti-qx80-windshields" },
    ] },
    { label: "Jaguar", href: "/vehicle-glass-repair/jaguar-windshield-replacements", children: [
      { label: "Jaguar E-Pace", href: "/vehicle-glass-repair/jaguar-e-pace" },
      { label: "Jaguar F-Pace", href: "/vehicle-glass-repair/jaguar-f-pace-windshield-replacement" },
      { label: "Jaguar F-Type", href: "/vehicle-glass-repair/jaguar-f-type" },
      { label: "Jaguar I-Pace", href: "/vehicle-glass-repair/jaguar-i-pace" },
      { label: "Jaguar InControl ADAS", href: "/vehicle-glass-repair/jaguar-adas-recalibration" },
      { label: "Jaguar XF", href: "/vehicle-glass-repair/jaguar-xf-windshield-replacement" },
    ] },
    { label: "Jeep", href: "/vehicle-glass-repair/jeep", children: [
      { label: "Jeep Active Driving Assist ADAS", href: "/vehicle-glass-repair/jeep-adas-recalibration" },
      { label: "Jeep Cherokee", href: "/vehicle-glass-repair/jeep-cherokee-windshields", children: [
        { label: "2017 Jeep Cherokee", href: "/vehicle-glass-repair/2017-jeep-cherokee" },
      ] },
      { label: "Jeep Compass", href: "/vehicle-glass-repair/jeep-compass" },
      { label: "Jeep Gladiator", href: "/vehicle-glass-repair/jeep-gladiator-windshield-replacement" },
      { label: "Jeep Grand Cherokee", href: "/vehicle-glass-repair/jeep-grand-cherokee", children: [
        { label: "2015 Jeep Grand Cherokee", href: "/vehicle-glass-repair/2015-jeep-grand-cherokee-windshields" },
      ] },
      { label: "Jeep Grand Wagoneer", href: "/vehicle-glass-repair/jeep-grand-wagoneer-windshield-replacement" },
      { label: "Jeep Overland", href: "/vehicle-glass-repair/jeep-overland-windshield-replacement" },
      { label: "Jeep Patriot", href: "/vehicle-glass-repair/jeep-patriot", children: [
        { label: "2016 Jeep Patriot", href: "/vehicle-glass-repair/2016-jeep-patriot" },
      ] },
      { label: "Jeep Recon", href: "/vehicle-glass-repair/jeep-recon-windshields" },
      { label: "Jeep Renegade", href: "/vehicle-glass-repair/jeep-renegade", children: [
        { label: "2017 Jeep Renegade", href: "/vehicle-glass-repair/2017-jeep-renegade" },
      ] },
      { label: "Jeep Wagoneer", href: "/vehicle-glass-repair/jeep-wagoneer-windshield-replacement" },
      { label: "Jeep Wagoneer S", href: "/vehicle-glass-repair/jeep-wagoneer-s-windshields" },
      { label: "Jeep Wrangler", href: "/vehicle-glass-repair/jeep-wrangler", children: [
        { label: "2016 Jeep Wrangler", href: "/vehicle-glass-repair/2016-jeep-wrangler-windshields" },
        { label: "2017 Jeep Wrangler", href: "/vehicle-glass-repair/2017-jeep-wrangler-windshields" },
      ] },
    ] },
    { label: "Kia", href: "/vehicle-glass-repair/kia-windshield-replacements", children: [
      { label: "Kia Cadenza", href: "/vehicle-glass-repair/kia-cadenza-windshields" },
      { label: "Kia Carnival", href: "/vehicle-glass-repair/kia-carnival-windshield-replacement" },
      { label: "KIA Drive Wise System", href: "/vehicle-glass-repair/kia-drive-wise-system-recalibration" },
      { label: "Kia EV6", href: "/vehicle-glass-repair/kia-ev6" },
      { label: "Kia EV9", href: "/vehicle-glass-repair/kia-ev9-windshields" },
      { label: "Kia Forte", href: "/vehicle-glass-repair/kia-forte-windshields" },
      { label: "Kia K4", href: "/vehicle-glass-repair/kia-k4-windshield-replacement" },
      { label: "Kia K4 Hatchback", href: "/vehicle-glass-repair/kia-k4-hatchback-windshields" },
      { label: "Kia K5", href: "/vehicle-glass-repair/kia-k5-windshield-replacement" },
      { label: "Kia Niro", href: "/vehicle-glass-repair/kia-niro-windshields" },
      { label: "Kia Optima", href: "/vehicle-glass-repair/kia-optima-windshields", children: [
        { label: "2016 Kia Optima", href: "/vehicle-glass-repair/2016-kia-optima-windshields" },
      ] },
      { label: "Kia Rio", href: "/vehicle-glass-repair/kia-rio-windshields" },
      { label: "Kia Sedona", href: "/vehicle-glass-repair/kia-sedona-windshields" },
      { label: "Kia Seltos", href: "/vehicle-glass-repair/kia-seltos-windshields" },
      { label: "Kia Sorento", href: "/vehicle-glass-repair/kia-sorento-windshields" },
      { label: "Kia Soul", href: "/vehicle-glass-repair/kia-soul-windshields", children: [
        { label: "2015 Kia Soul", href: "/vehicle-glass-repair/2015-kia-soul" },
      ] },
      { label: "Kia Sportage", href: "/vehicle-glass-repair/kia-sportage-windshield-replacements" },
      { label: "Kia Stinger", href: "/vehicle-glass-repair/kia-stinger-windshield-replacement" },
      { label: "Kia Telluride", href: "/vehicle-glass-repair/kia-telluride-windshields" },
    ] },
    { label: "Land Rover", href: "/vehicle-glass-repair/land-rover", children: [
      { label: "Land Rover Autobiography", href: "/vehicle-glass-repair/land-rover-autobiography-windshield-replacement" },
      { label: "Land Rover Defender", href: "/vehicle-glass-repair/land-rover-defender-windshield" },
      { label: "Land Rover Discovery", href: "/vehicle-glass-repair/land-rover-discovery-windshield-replacement" },
      { label: "Land Rover Discovery Sport", href: "/vehicle-glass-repair/land-rover-discovery-sport-windshield-replacement" },
      { label: "Land Rover InControl ADAS", href: "/vehicle-glass-repair/land-rover-adas-recalibration" },
      { label: "Range Rover", href: "/vehicle-glass-repair/range-rover-windshield-replacements" },
      { label: "Range Rover Evoque", href: "/vehicle-glass-repair/range-rover-evoque-windshields" },
      { label: "Range Rover Sport", href: "/vehicle-glass-repair/range-rover-sport-windshields" },
      { label: "Range Rover Velar", href: "/vehicle-glass-repair/range-rover-velar-windshields" },
    ] },
    { label: "Lexus", href: "/vehicle-glass-repair/lexus", children: [
      { label: "Lexus ES", href: "/vehicle-glass-repair/lexus-es-windshield-replacement" },
      { label: "Lexus ES 350", href: "/vehicle-glass-repair/lexus-es-350-windshield-replacement" },
      { label: "Lexus GX 460", href: "/vehicle-glass-repair/lexus-gx-460-windshield-replacement" },
      { label: "Lexus IS 250", href: "/vehicle-glass-repair/lexus-is-250-windshield-replacement" },
      { label: "Lexus IS 300", href: "/vehicle-glass-repair/lexus-is-300-windshield-replacement" },
      { label: "Lexus IS 350", href: "/vehicle-glass-repair/lexus-is350" },
      { label: "Lexus IS 500", href: "/vehicle-glass-repair/lexus-is500" },
      { label: "Lexus LC", href: "/vehicle-glass-repair/lexus-lc-windshields" },
      { label: "Lexus LS 500", href: "/vehicle-glass-repair/lexus-ls-500-windshield-replacement" },
      { label: "Lexus LX 570", href: "/vehicle-glass-repair/lexus-lx-570-windshield-replacement" },
      { label: "Lexus NX 300", href: "/vehicle-glass-repair/lexus-nx-300-windshield-replacement" },
      { label: "Lexus NX 300h", href: "/vehicle-glass-repair/lexus-nx-300h-windshield-replacement" },
      { label: "Lexus RC 350", href: "/vehicle-glass-repair/lexus-rc-350-windshield-replacement" },
      { label: "Lexus RX", href: "/vehicle-glass-repair/lexus-rx" },
      { label: "Lexus RX 350", href: "/vehicle-glass-repair/lexus-rx-350-windshield-replacement" },
      { label: "Lexus RX 450h", href: "/vehicle-glass-repair/lexus-rx-450h-windshield-replacement" },
      { label: "Lexus RZ 300E", href: "/vehicle-glass-repair/lexus-rz-300e-windshield-replacement" },
      { label: "Lexus Safety System+", href: "/vehicle-glass-repair/lexus-safety-system-adas-recalibration" },
      { label: "Lexus TX 350", href: "/vehicle-glass-repair/lexus-tx-350-windshield-replacement" },
      { label: "Lexus UX", href: "/vehicle-glass-repair/lexus-ux-windshield-replacement" },
    ] },
    { label: "Lincoln", href: "/vehicle-glass-repair/lincoln-windshield-replacements", children: [
      { label: "Lincoln Aviator", href: "/vehicle-glass-repair/lincoln-aviator-windshield-replacement" },
      { label: "Lincoln Co-Pilot360 ADAS", href: "/vehicle-glass-repair/lincoln-adas-recalibration" },
      { label: "Lincoln Continental", href: "/vehicle-glass-repair/lincoln-continental-windshield-replacement" },
      { label: "Lincoln Corsair", href: "/vehicle-glass-repair/lincoln-corsair-windshield-replacement" },
      { label: "Lincoln MKZ", href: "/vehicle-glass-repair/lincoln-mkz-windshield-replacement" },
      { label: "Lincoln Nautilus", href: "/vehicle-glass-repair/lincoln-nautilus-windshield-replacement" },
      { label: "Lincoln Navigator", href: "/vehicle-glass-repair/lincoln-navigator-windshield-replacement" },
    ] },
    { label: "Lucid", href: "/vehicle-glass-repair/lucid-windshield-replacements", children: [
      { label: "Lucid Air", href: "/vehicle-glass-repair/lucid-air-windshield" },
    ] },
    { label: "Mazda", href: "/vehicle-glass-repair/mazda-windshield-replacements", children: [
      { label: "Mazda 3", href: "/vehicle-glass-repair/mazda3-windshields" },
      { label: "Mazda 6", href: "/vehicle-glass-repair/mazda6-windshields" },
      { label: "Mazda ADAS", href: "/vehicle-glass-repair/mazda-adas-recalibration" },
      { label: "Mazda CX-30", href: "/vehicle-glass-repair/mazda-cx-30-windshield-replacement" },
      { label: "Mazda CX-5", href: "/vehicle-glass-repair/mazda-cx-5-windshields", children: [
        { label: "2016 Mazda CX-5", href: "/vehicle-glass-repair/2016-mazda-cx-5-windshields" },
      ] },
      { label: "Mazda CX-50", href: "/vehicle-glass-repair/mazda-cx-50" },
      { label: "Mazda CX-70", href: "/vehicle-glass-repair/mazda-cx-70-windshield-replacement" },
      { label: "Mazda CX-90", href: "/vehicle-glass-repair/mazda-cx-90-windshield-replacement" },
      { label: "Mazda CX-9", href: "/vehicle-glass-repair/mazda-cx-9-windshields" },
      { label: "Mazda MX-5", href: "/vehicle-glass-repair/mazda-mx5-miata" },
    ] },
    { label: "Mercedes-Benz", href: "/vehicle-glass-repair/mercedes-benz", children: [
      { label: "Mercedes-Benz ADAS Sensing", href: "/vehicle-glass-repair/mercedes-benz-sensing-adas-recalibration" },
      { label: "Mercedes-Benz AMG SL 43", href: "/vehicle-glass-repair/mercedes-benz-amg-sl-43-windshield-replacement" },
      { label: "Mercedes-Benz CLA", href: "/vehicle-glass-repair/mercedes-benz-cla-windshields" },
      { label: "Mercedes-Benz CLE Cabriolet", href: "/vehicle-glass-repair/mercedes-benz-cle-cabriolet" },
      { label: "Mercedes-Benz CLS", href: "/vehicle-glass-repair/mercedes-benz/mercedes-benz-cls" },
      { label: "Mercedes-Benz E-Class", href: "/vehicle-glass-repair/mercedes-benz-e-class" },
      { label: "Mercedes-Benz E300", href: "/vehicle-glass-repair/mercedes-benz-e300-windshields" },
      { label: "Mercedes-Benz E350", href: "/vehicle-glass-repair/mercedes-benz-E350-windshields" },
      { label: "Mercedes-Benz G-Class", href: "/vehicle-glass-repair/mercedes-benz/mercedes-benz-g-class" },
      { label: "Mercedes-Benz GLE-Class", href: "/vehicle-glass-repair/mercedes-benz-gle-windshields" },
      { label: "Mercedes-Benz GLE350", href: "/vehicle-glass-repair/mercedes-benz-gle350-windshields" },
      { label: "Mercedes-Benz GLE43 AMG", href: "/vehicle-glass-repair/mercedes-benz-gle43-amg-windshields" },
      { label: "Mercedes-Benz GLE450", href: "/vehicle-glass-repair/mercedes-benz-gle450-windshields" },
      { label: "Mercedes-Benz GLS-Class", href: "/vehicle-glass-repair/mercedes-benz-gls-windshields" },
      { label: "Mercedes-Benz GLS450", href: "/vehicle-glass-repair/mercedes-benz-gls450-windshields" },
      { label: "Mercedes-Benz ML350", href: "/vehicle-glass-repair/mercedes-benz-ml350-windshields" },
      { label: "Mercedes-Benz Metris", href: "/vehicle-glass-repair/mercedes-benz-metris-windshield-replacement" },
      { label: "Mercedes-Benz s450", href: "/vehicle-glass-repair/mercedes-benz/mercedes-benz-s450" },
      { label: "Mercedes-Benz s550", href: "/vehicle-glass-repair/mercedes-benz/mercedes-benz-s550" },
      { label: "Mercedes-Benz s560", href: "/vehicle-glass-repair/mercedes-benz/mercedes-benz-s560" },
      { label: "Mercedes SL Roadster", href: "/vehicle-glass-repair/mercedes-benz-sl-roadster" },
    ] },
    { label: "Mercury", href: "/vehicle-glass-repair/mercury-windshield-replacements", children: [
      { label: "Mercury Milan", href: "/vehicle-glass-repair/mercury-milan" },
      { label: "Mercury Mountaineer", href: "/vehicle-glass-repair/mercury-mountaineer" },
    ] },
    { label: "MINI", href: "/vehicle-glass-repair/mini-windshield-replacements", children: [
      { label: "Mini Active Driving Assistant ADAS", href: "/vehicle-glass-repair/mini-adas-recalibration" },
      { label: "Mini Clubman", href: "/vehicle-glass-repair/mini-clubman-windshield-replacement" },
      { label: "Mini Convertible", href: "/vehicle-glass-repair/mini-convertible-windshield-replacement" },
      { label: "Mini Countryman", href: "/vehicle-glass-repair/mini-countryman-windshield-replacement" },
      { label: "Mini Hardtop", href: "/vehicle-glass-repair/mini-hardtop-windshield-replacement" },
      { label: "Mini Paceman", href: "/vehicle-glass-repair/mini-paceman-windshield-replacement" },
    ] },
    { label: "Mitsubishi", href: "/vehicle-glass-repair/mitsubishi-windshield-replacements", children: [
      { label: "Mitsubishi Eclipse", href: "/vehicle-glass-repair/mitsubishi-eclipse-windshield-replacements" },
      { label: "Mitsubishi Eclipse Cross", href: "/vehicle-glass-repair/mitsubishi-eclipse-windshield-cross-replacements" },
      { label: "Mitsubishi Endeavor", href: "/vehicle-glass-repair/mitsubishi-endeavor-windshield-replacements" },
      { label: "Mitsubishi MI-PILOT ADAS", href: "/vehicle-glass-repair/mitsubishi-adas-recalibration" },
      { label: "Mitsubishi Mirage", href: "/vehicle-glass-repair/mitsubishi-mirage-windshield-replacement" },
      { label: "Mitsubishi Outlander", href: "/vehicle-glass-repair/mitsubishi-outlander-windshield-replacements" },
      { label: "Mitsubishi Outlander Sport", href: "/vehicle-glass-repair/mitsubishi-outlander-windshield-sport-replacements" },
    ] },
    { label: "Nissan", href: "/vehicle-glass-repair/nissan-windshield-replacements", children: [
      { label: "Nissan Altima", href: "/vehicle-glass-repair/nissan-altima-windshields", children: [
        { label: "2008 Nissan Altima", href: "/vehicle-glass-repair/2008-nissan-altima-windshields" },
        { label: "2013 Nissan Altima", href: "/vehicle-glass-repair/2013-nissan-altima-windshields" },
        { label: "2015 Nissan Altima", href: "/vehicle-glass-repair/2015-nissan-altima-windshields" },
        { label: "2017 Nissan Altima", href: "/vehicle-glass-repair/2017-nissan-altima-windshields" },
      ] },
      { label: "Nissan Armada", href: "/vehicle-glass-repair/nissan-armada-windshield-replacement" },
      { label: "Nissan Aryia", href: "/vehicle-glass-repair/nissan-ariya-windshields" },
      { label: "Nissan Frontier", href: "/vehicle-glass-repair/nissan-frontier-windshield-replacement" },
      { label: "Nissan Juke", href: "/vehicle-glass-repair/nissan-juke-windshield-replacement" },
      { label: "Nissan Kicks", href: "/vehicle-glass-repair/nissan-kicks-windshield-replacement" },
      { label: "Nissan Leaf", href: "/vehicle-glass-repair/nissan-leaf-windshield-replacement" },
      { label: "Nissan Maxima", href: "/vehicle-glass-repair/nissan-maxima-windshields" },
      { label: "Nissan Murano", href: "/vehicle-glass-repair/nissan-murano-windshields" },
      { label: "Nissan Pathfinder", href: "/vehicle-glass-repair/nissan-pathfinder-windshield-replacement" },
      { label: "Nissan Rogue", href: "/vehicle-glass-repair/nissan-rogue-windshields", children: [
        { label: "2016 Nissan Rogue", href: "/vehicle-glass-repair/2016-nissan-rogue-windshields" },
        { label: "2017 Nissan Rogue Sport", href: "/vehicle-glass-repair/2017-nissan-rogue-sport-windshields" },
      ] },
      { label: "Nissan Rouge Sport", href: "/vehicle-glass-repair/nissan-rogue-sport-windshields" },
      { label: "Nissan Safety Shield", href: "/vehicle-glass-repair/nissan-safety-shield-recalibration" },
      { label: "Nissan Sentra", href: "/vehicle-glass-repair/nissan-sentra-windshields" },
      { label: "Nissan Titan", href: "/vehicle-glass-repair/nissan-titan-windshield-replacement" },
      { label: "Nissan Versa", href: "/vehicle-glass-repair/nissan-versa-windshield-replacement" },
      { label: "Nissan Xterra", href: "/vehicle-glass-repair/nissan-xterra-windshields" },
      { label: "Nissan Z", href: "/vehicle-glass-repair/nissan-z-windshields" },
    ] },
    { label: "Polestar", href: "/vehicle-glass-repair/polestar-windshield-replacements", children: [
      { label: "Polestar 2", href: "/vehicle-glass-repair/polestar-2-windshields" },
    ] },
    { label: "Pontiac", href: "/vehicle-glass-repair/pontiac-windshield-replacements", children: [
      { label: "Pontiac G6", href: "/vehicle-glass-repair/pontiac-g6" },
      { label: "Pontiac Vibe", href: "/vehicle-glass-repair/pontiac-vibe" },
    ] },
    { label: "Porsche", href: "/vehicle-glass-repair/porsche-windshield-replacements", children: [
      { label: "Porsche 718", href: "/vehicle-glass-repair/porsche-718" },
      { label: "Porsche 911", href: "/vehicle-glass-repair/porsche-911-windshield-replacement" },
      { label: "Porsche Boxster", href: "/vehicle-glass-repair/porsche-boxster-windshield-replacement" },
      { label: "Porsche Cayenne", href: "/vehicle-glass-repair/porsche-cayenne-windshield-replacement" },
      { label: "Porsche Cayman", href: "/vehicle-glass-repair/porsche-cayman-windshields" },
      { label: "Porsche Macan", href: "/vehicle-glass-repair/porsche-macan-windshield-replacement" },
      { label: "Porsche Panamera", href: "/vehicle-glass-repair/porsche-panamera-windshield-replacement" },
      { label: "Porsche Taycan", href: "/vehicle-glass-repair/porsche-taycan-windshield-replacement" },
    ] },
    { label: "Ram", href: "/vehicle-glass-repair/ram-windshield-replacements", children: [
      { label: "Ram 1500", href: "/vehicle-glass-repair/ram-1500-windshields" },
      { label: "Ram 1500 REV", href: "/vehicle-glass-repair/ram-1500-rev-windshields" },
      { label: "Ram 2500", href: "/vehicle-glass-repair/ram-2500-windshields" },
      { label: "Ram 3500", href: "/vehicle-glass-repair/ram-3500-windshields" },
      { label: "Ram Chassis Cab", href: "/vehicle-glass-repair/ram-chassis-cab-windshields" },
      { label: "Ram ProMaster", href: "/vehicle-glass-repair/ram-promaster-windshields" },
    ] },
    { label: "Rivian", href: "/vehicle-glass-repair/rivian-windshield-repairs", children: [
      { label: "Rivian R1S", href: "/vehicle-glass-repair/rivian-r1s-windshields" },
      { label: "Rivian R1T", href: "/vehicle-glass-repair/rivian-r1t-windshields" },
      { label: "Rivian R2", href: "/vehicle-glass-repair/rivian-r2-windshields" },
      { label: "Rivian R3", href: "/vehicle-glass-repair/rivian-r3-windshields" },
    ] },
    { label: "Saab", href: "/vehicle-glass-repair/saab-windshield-replacements", children: [
      { label: "Saab 9-3", href: "/vehicle-glass-repair/saab-9-3" },
      { label: "Saab 9-5", href: "/vehicle-glass-repair/saab-9-5" },
    ] },
    { label: "Subaru", href: "/vehicle-glass-repair/subaru-windshield-replacements", children: [
      { label: "Subaru Ascent", href: "/vehicle-glass-repair/subaru-ascent-windshield-replacement" },
      { label: "Subaru BRZ", href: "/vehicle-glass-repair/subaru-brz-windshield-replacement" },
      { label: "Subaru Crosstrek", href: "/vehicle-glass-repair/subaru-crosstrek-windshields" },
      { label: "Subaru Crosstrek Hybrid", href: "/vehicle-glass-repair/subaru-crosstrek-hybrid-windshields" },
      { label: "Subaru EyeSight", href: "/vehicle-glass-repair/subaru-eyesight-adas-recalibration" },
      { label: "Subaru Forester", href: "/vehicle-glass-repair/subaru-forester-windshields" },
      { label: "Subaru Forester Hybrid", href: "/vehicle-glass-repair/subaru-forester-hybrid-windshields" },
      { label: "Subaru Impreza", href: "/vehicle-glass-repair/subaru-impreza-windshields" },
      { label: "Subaru Legacy", href: "/vehicle-glass-repair/subaru-legacy-windshields" },
      { label: "Subaru Outback", href: "/vehicle-glass-repair/subaru-outback-windshields", children: [
        { label: "2016 Subaru Outback", href: "/vehicle-glass-repair/2016-subaru-outback-windshields" },
      ] },
      { label: "Subaru Solterra", href: "/vehicle-glass-repair/subaru-solterra-windshield-replacement" },
      { label: "Subaru Trailseeker", href: "/vehicle-glass-repair/subaru-trailseeker-windshields" },
      { label: "Subaru Uncharted", href: "/vehicle-glass-repair/subaru-uncharted-windshields" },
      { label: "Subaru Wilderness", href: "/vehicle-glass-repair/subaru-wilderness-windshield-replacement" },
      { label: "Subaru WRX", href: "/vehicle-glass-repair/subaru-wrx-windshields" },
    ] },
    { label: "Suzuki", href: "/vehicle-glass-repair/suzuki-windshield-replacements" },
    { label: "Tesla", href: "/vehicle-glass-repair/tesla-windshield-replacements", children: [
      { label: "Tesla Autopilot ADAS", href: "/vehicle-glass-repair/tesla-adas-recalibration" },
      { label: "Tesla Cybertruck", href: "/vehicle-glass-repair/tesla-cybertruck" },
      { label: "Tesla Model 3", href: "/vehicle-glass-repair/tesla-windshield-replacements/tesla-model-3" },
      { label: "Tesla Model S", href: "/vehicle-glass-repair/tesla-windshield-replacements/tesla-model-s" },
      { label: "Tesla Model X", href: "/vehicle-glass-repair/tesla-windshield-replacements/tesla-model-x" },
      { label: "Tesla Model Y", href: "/vehicle-glass-repair/tesla-windshield-replacements/tesla-model-y" },
    ] },
    { label: "Toyota", href: "/vehicle-glass-repair/toyota-windshield-replacements", children: [
      { label: "Toyota 4Runner", href: "/vehicle-glass-repair/toyota-4runner-windshield-replacement" },
      { label: "Toyota Avalon", href: "/vehicle-glass-repair/toyota-avalon-windshield-replacement" },
      { label: "Toyota bZ4X", href: "/vehicle-glass-repair/toyota-bz4x-windshield-replacement" },
      { label: "Toyota Camry", href: "/vehicle-glass-repair/toyota-camry-windshields", children: [
        { label: "2009 Toyota Camry", href: "/vehicle-glass-repair/2009-toyota-camry-windshields" },
        { label: "2018 Toyota Camry", href: "/vehicle-glass-repair/2018-toyota-camry-windshields" },
      ] },
      { label: "Toyota C-HR", href: "/vehicle-glass-repair/toyota-c-hr-windshields" },
      { label: "Toyota Corolla", href: "/vehicle-glass-repair/toyota-corolla-windshields", children: [
        { label: "2010 Toyota Corolla", href: "/vehicle-glass-repair/2010-toyota-corolla-windshields" },
        { label: "2016 Toyota Corolla", href: "/vehicle-glass-repair/2016-toyota-corolla-windshields" },
      ] },
      { label: "Toyota Corolla Cross", href: "/vehicle-glass-repair/toyota-corolla-cross-windshields" },
      { label: "Toyota Crown", href: "/vehicle-glass-repair/toyota-crown-windshield-replacement" },
      { label: "Toyota Crown Signia", href: "/vehicle-glass-repair/toyota-crown-signia-windshield-replacement" },
      { label: "Toyota GR86", href: "/vehicle-glass-repair/toyota-gr86-windshields" },
      { label: "Toyota GR Corolla", href: "/vehicle-glass-repair/toyota-gr-corolla-windshields" },
      { label: "Toyota Grand Highlander", href: "/vehicle-glass-repair/toyota-grand-highlander-windshields" },
      { label: "Toyota Highlander", href: "/vehicle-glass-repair/toyota-highlander-windshields" },
      { label: "Toyota Land Cruiser", href: "/vehicle-glass-repair/toyota-land-cruiser-windshield-replacement" },
      { label: "Toyota Mirai", href: "/vehicle-glass-repair/toyota-mirai-windshields" },
      { label: "Toyota Prius", href: "/vehicle-glass-repair/toyota-prius-windshields" },
      { label: "Toyota Prius Prime", href: "/vehicle-glass-repair/toyota-prius-prime-windshields" },
      { label: "Toyota Rav4", href: "/vehicle-glass-repair/toyota-rav4-windshields", children: [
        { label: "2017 Toyota Rav4", href: "/vehicle-glass-repair/2017-toyota-rav4-windshields" },
      ] },
      { label: "Toyota Safety Sense", href: "/toyota-windshield-replacements/toyota-safety-sense" },
      { label: "Toyota Sequoia", href: "/vehicle-glass-repair/toyota-sequoia-windshield-replacement" },
      { label: "Toyota Sienna", href: "/vehicle-glass-repair/toyota-sienna-windshields", children: [
        { label: "2015 Toyota Sienna", href: "/vehicle-glass-repair/2015-toyota-sienna-windshields" },
      ] },
      { label: "Toyota Supra", href: "/vehicle-glass-repair/toyota-supra-windshields" },
      { label: "Toyota Tacoma", href: "/vehicle-glass-repair/toyota-tacoma-windshields", children: [
        { label: "2017 Toyota Tacoma", href: "/vehicle-glass-repair/2017-toyota-tacoma-windshields" },
      ] },
      { label: "Toyota Tundra", href: "/vehicle-glass-repair/toyota-tundra-windshields" },
      { label: "Toyota Venza", href: "/vehicle-glass-repair/toyota-venza-windshield-replacement" },
      { label: "Toyota Yaris", href: "/vehicle-glass-repair/toyota-yaris-windshield-replacement" },
    ] },
    { label: "Volkswagen", href: "/vehicle-glass-repair/volkswagen-windshield-replacements", children: [
      { label: "Volkswagen ADAS", href: "/vehicle-glass-repair/volkswagen-adas-recalibration" },
      { label: "Volkswagen Arteon", href: "/vehicle-glass-repair/volkswagen-arteon-windshield-replacement" },
      { label: "Volkswagen Atlas", href: "/vehicle-glass-repair/volkswagen-atlas-windshields" },
      { label: "Volkswagen Atlas Cross Sport", href: "/vehicle-glass-repair/volkswagen-atlas-cross-sport-windshields" },
      { label: "Volkswagen Beetle", href: "/vehicle-glass-repair/volkswagen-beetle-windshields" },
      { label: "Volkswagen Golf", href: "/vehicle-glass-repair/volkswagen-golf-windshield-replacement" },
      { label: "Volkswagen GTI", href: "/vehicle-glass-repair/volkswagen-gti-windshield-replacement" },
      { label: "Volkswagen ID 4", href: "/vehicle-glass-repair/volkswagen-id-4-windshields" },
      { label: "Volkswagen ID Buzz", href: "/vehicle-glass-repair/volkswagen-id-buzz-windshields" },
      { label: "Volkswagen Jetta", href: "/vehicle-glass-repair/volkswagen-jetta-windshields", children: [
        { label: "2014 Volkswagen Jetta", href: "/vehicle-glass-repair/2014-volkswagen-jetta-windshields" },
      ] },
      { label: "Volkswagen Jetta GLI", href: "/vehicle-glass-repair/volkswagen-jetta-gli" },
      { label: "Volkswagen Passat", href: "/vehicle-glass-repair/volkswagen-passat-windshields" },
      { label: "Volkswagen Taos", href: "/vehicle-glass-repair/volkswagen-taos-windshield-replacement" },
      { label: "Volkswagen Tiguan", href: "/vehicle-glass-repair/volkswagen-tiguan-windshields" },
    ] },
    { label: "Volvo", href: "/vehicle-glass-repair/volvo-windshield-replacements", children: [
      { label: "Volvo ADAS", href: "/vehicle-glass-repair/volvo-adas-recalibration" },
      { label: "Volvo C40", href: "/vehicle-glass-repair/volvo-c40" },
      { label: "Volvo EX30", href: "/vehicle-glass-repair/volvo-ex30" },
      { label: "Volvo EX40", href: "/vehicle-glass-repair/volvo-ex40-windshields" },
      { label: "Volvo EX90", href: "/vehicle-glass-repair/volvo-ex90" },
      { label: "Volvo S40", href: "/vehicle-glass-repair/volvo-s40-windshields" },
      { label: "Volvo S60", href: "/vehicle-glass-repair/volvo-s60" },
      { label: "Volvo S90", href: "/vehicle-glass-repair/volvo-s90" },
      { label: "Volvo V60", href: "/vehicle-glass-repair/volvo-v60" },
      { label: "Volvo XC40", href: "/vehicle-glass-repair/volvo-xc40-windshield-replacement" },
      { label: "Volvo XC60", href: "/vehicle-glass-repair/volvo-xc60-windshields" },
      { label: "Volvo XC70", href: "/vehicle-glass-repair/volvo-xc70-windshields" },
      { label: "Volvo XC90", href: "/vehicle-glass-repair/volvo-xc90-windshields" },
    ] },
  ] },
  { label: "Why choose Safelite", href: "/why-choose-safelite", children: [
    { label: "Mobile and in-shop", href: "/mobile-auto-glass-repair" },
    { label: "Safelite Advantage", href: "/the-safelite-advantage" },
    { label: "Glass recycling", href: "/why-choose-safelite/glass-recycling" },
  ] },
  { label: "Beyond the glass", href: "/windshield-auto-glass-technology", children: [
    { label: "Windshield", href: "/windshield-auto-glass-technology/windshield" },
    { label: "Rear windshield", href: "/windshield-auto-glass-technology/rear-windshield" },
    { label: "Side glass", href: "/windshield-auto-glass-technology/side-window" },
    { label: "Vent glass", href: "/windshield-auto-glass-technology/vent-window" },
    { label: "Quarter glass", href: "/windshield-auto-glass-technology/quarter-glass" },
    { label: "Sliders", href: "/windshield-auto-glass-technology/truck-sliders" },
    { label: "Sunroof", href: "/windshield-auto-glass-technology/sunroof" },
    { label: "ADAS", href: "/windshield-auto-glass-technology/adas" },
    { label: "Light sensor", href: "/windshield-auto-glass-technology/headlight-sensors" },
    { label: "Rain sensor", href: "/windshield-auto-glass-technology/rain-sensors" },
    { label: "VIN", href: "/windshield-auto-glass-technology/vin" },
    { label: "Heads-up display", href: "/windshield-auto-glass-technology/heads-up-display" },
    { label: "Infrared", href: "/windshield-auto-glass-technology/infrared-windshield-glass" },
    { label: "Heated", href: "/windshield-auto-glass-technology/heated-windshields" },
    { label: "Shade band", href: "/windshield-auto-glass-technology/visor-strips" },
    { label: "Night vision", href: "/windshield-auto-glass-technology/night-vision" },
  ] },
  { label: "Help center", href: "/help-center", children: [
    { label: "Glass damage and service", href: "/help-center/glass-damage-and-service", children: [
      { label: "Glass damage", href: "/help-center/glass-damage-and-service/glass-damage" },
      { label: "Service expectations", href: "/help-center/glass-damage-and-service/service-expectations" },
      { label: "Services & products", href: "/help-center/glass-damage-and-service/services-and-products" },
    ] },
    { label: "Preparing for your appointment", href: "/help-center/preparing-for-your-appointment", children: [
      { label: "Preparation", href: "/help-center/preparing-for-your-appointment/preparation" },
      { label: "Installation", href: "/help-center/preparing-for-your-appointment/installation" },
    ] },
    { label: "Cost, payment, and billing", href: "/help-center/cost", children: [
      { label: "Service cost", href: "/help-center/cost/service-cost" },
      { label: "Payment & billing", href: "/help-center/cost/payment-and-billing" },
    ] },
    { label: "Insurance coverage and claims", href: "/help-center/insurance-coverage" },
    { label: "Warranty details", href: "/help-center/warranty" },
    { label: "Marketing and privacy", href: "/help-center/marketing-and-privacy" },
    { label: "Mobile Glass Service FAQs", href: "/help-center/mobile-service" },
    { label: "Auto Glass Repair FAQs", href: "/help-center/repair" },
    { label: "What to Expect FAQs", href: "/help-center/what-to-expect" },
    { label: "About Safelite FAQs", href: "/help-center/about-us" },
    { label: "Our Glass FAQs", href: "/help-center/our-glass" },
    { label: "Our Services FAQs", href: "/help-center/our-services" },
  ] },
  { label: "Resource Center", href: "/resource-center", children: [
    { label: "Category", href: "/resource-center/category", children: [
      { label: "Auto Expertise", href: "/resource-center/category/auto-experts" },
      { label: "Culture", href: "/resource-center/category/culture" },
      { label: "Current events", href: "/resource-center/category/current-events" },
      { label: "Safety", href: "/resource-center/category/car-safety" },
    ] },
    { label: "Past articles", href: "/resource-center/archive" },
    { label: "The Ultimate Commuter Quiz", href: "/resource-center/the-ultimate-commuter-quiz" },
    { label: "Celebrity Car Quiz", href: "/resource-center/celebrity-car-quiz" },
    { label: "How much does your car mean to you", href: "/resource-center/car-love-quiz" },
  ] },
  { label: "Recalibration Web Story", href: "/story" },
  { label: "Your privacy choices", href: "/privacy-center" },
  { label: "Liberty Mutual Windshield Replacement", href: "/moe-windshield-replacement" },
  { label: "USAA Windshield Replacement", href: "/usaa-windshield-replacement" },
  { label: "Farmers Windshield Replacement", href: "/farmers-windshield-repair-replacement", children: [
    { label: "Safeco Windshield Replacement", href: "/safeco-windshield-replacement" },
  ] },
  { label: "Allstate Windshield Replacement", href: "/allstate-windshield-replacement" },
  { label: "Nationwide Windshield Replacement", href: "/nationwide-windshield-replacement" },
  { label: "Westfield Windshield Replacement", href: "/westfield-windshield-replacement" },
  { label: "Cost of Auto Glass Services", href: "/auto-glass-repair-replacement-cost" },
  { label: "Glass damage type", href: "/damaged-windshield-repair-replace" },
  { label: "COUNTRY Financial Windshield Replacement", href: "/country-financial-windshield-replacement" },
  { label: "PEMCO Windshield Replacement", href: "/pemco-windshield-replacement" },
  { label: "Enumclaw Windshield Replacement", href: "/enumclaw-windshield-replacement" },
];
