// Snapshot of the first nine pages (five reviews each) of the Yotpo reviews
// widget on safelite.com/auto-glass-services/safelite-reviews.

export type Review = {
  id: string;
  name: string;
  verified: boolean;
  // Date as the widget prints it (MM/DD/YY)
  date: string;
  score: number;
  title: string;
  // Text shown first. Line breaks are "\n".
  content: string;
  // Rest of a long review, revealed by "Read More"
  more?: string;
  votesUp: number;
  votesDown: number;
  photo?: { src: string; alt: string };
};

export const REVIEWS_PER_PAGE = 5;

// Total shown in the ratings summary
export const TOTAL_REVIEWS = 1122338;

export const REVIEWS: Review[] = [
  {
    id: "895234601",
    name: "Scott B.",
    verified: false,
    date: "09/29/26",
    score: 5,
    title: "Windshield replacement",
    content: "The installer showed up on time, was very professional and did a great job. I would use Safelite again in the future if needed.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895232743",
    name: "Sam",
    verified: true,
    date: "09/29/26",
    score: 5,
    title: "Windshield Replacement",
    content: "Convenient scheduling and completed as advertised with no issues",
    votesUp: 1,
    votesDown: 0,
  },
  {
    id: "895229980",
    name: "Marion Y.",
    verified: true,
    date: "09/29/26",
    score: 5,
    title: "Mark was wonderful. Very professional,",
    content: "Mark was wonderful. Very professional, knowledgeable and informative.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895228036",
    name: "Kim",
    verified: false,
    date: "09/29/26",
    score: 5,
    title: "Service",
    content: "work was completed on time and professionally",
    votesUp: 0,
    votesDown: 1,
  },
  {
    id: "895227064",
    name: "Joni Y.",
    verified: true,
    date: "09/29/26",
    score: 5,
    title: "Excellent service",
    content: "I’m very pleased with how smooth the booking process was and the notifications to keep me updated was very helpful. My tech, Jamil, was awesome. I enjoyed watching the process of replacing a windshield. Thank you.",
    votesUp: 1,
    votesDown: 1,
  },
  {
    id: "895219230",
    name: "Kat R.",
    verified: true,
    date: "09/29/26",
    score: 5,
    title: "Excellent",
    content: "Courteous efficient skilled",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895157689",
    name: "saren",
    verified: true,
    date: "09/29/26",
    score: 5,
    title: "Great service!",
    content: "The technician Diego was quick with the repair,and we had a good experience! it was very convenient with Safelite auto glass.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895155204",
    name: "Anne L.",
    verified: false,
    date: "09/29/26",
    score: 5,
    title: "Windshield replacement",
    content: "Great experience. Easy from working with insurance to scheduling to preparation to completion. Friendly, professional representatives representatives! Thank you..",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895153278",
    name: "Jim",
    verified: true,
    date: "09/29/26",
    score: 5,
    title: "Professional and courteous!",
    content: "Professional and courteous!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895146496",
    name: "Heather B.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Autoglass Repair",
    content: "My front windshield was repaired on Sept 10th! From start to finish the process was seamless. Booking the appointment online was made simple and they were able to come to my home the next day! Michael in Greenville/ Spartanburg, SC area was my technician and he was excellent! He texted me the morning of letting me know what time he should arrive a",
    more: "nd called approx. 30 minutes prior to let me know he was on his way! We immediately bonded over my vehicle and love for the Air1 Worship radio station. He was so kind and courteous and completed the window repair in approx. 45 minutes- letting me know I had a brand new window! I could not have asked for a better experience! I am so appreciative of Michael and Safelite for my windshield repair! Thank you again! ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895145518",
    name: "Chris B.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "Replacement",
    content: "Amazing job on my window replacement! Easy online appointment making process, easier in store process! Great job and will definitely recommend to anyone that needs a repair or replacement!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895140313",
    name: "Thinh N.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "Excelent service",
    content: "Very flexible to schedule at home service with skilled technician that the job can be done professionally. I just prepared a shade space in garage then he'll come to complete everything within an hour with installation and calibration.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895140191",
    name: "Christopher H.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Stellar Work",
    content: "I had my front windshield replaced on my 2021 Mazda CX5 today (09-28-2026) by Steve and he performed very clean and timely work. He let me know exactly when he would be here and arrived on the dot. Windshield looks good as new and no issues whatsoever. He was thoughtful enough to ask me how I would like him to work around some aftermarket mods I h",
    more: "ave located near and around my windshield. He performed the recalibration for my collision prevention system and everything. I have a total of 3” of additional ground clearance with the lift and oversized tires, but he managed to ensure the calibration was spot on according my vehicles height. Overall superior work! Thanks Steve! ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895139199",
    name: "Karen W.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "Great Experience",
    content: "Great communication from the beginning. Prompt, friendly and efficient. Very professional job. Would use again.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895138412",
    name: "Michelle G.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "Excellent, Professional, convenient!",
    content: "The techs did excellent work and were extremely professional. They kept me well informed about their arrival time and how long the job would take. Safelite is so convenient, I can’t imagine why any one would choose another option.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895138319",
    name: "Louis M.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "The whole windshield replacement process",
    content: "The whole windshield replacement process was a breeze. It was quick and easy all the way around. The two tech. guys were great. They represented Safelite in an excellent manner. It was a pleasure doing business with them. Thank You",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895137308",
    name: "Matt",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Professional service",
    content: "The Safelite technician Jordan was on time, professional and performed the service perfectly and within the suggested timeframe.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895136225",
    name: "Mark F.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Great Service",
    content: "We needed a Jeep windshield replaced and we used the online scheduler to set up our appointment. It was surprisingly easy and efficient to schedule. We received multiple texts and voice mails regarding our selected time as well as a photo of our technician, all great. He showed up on time and completed the work in the time he quoted. Very good exp",
    more: "erience, would highly recommend Safelight. ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895135672",
    name: "eileen",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "review",
    content: "great service, super friendly tech. windshield looks great",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895135398",
    name: "Cliff D.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Excellent From Start to Finish",
    content: "Very pleased with technician Ian from Safelite. I was able to schedule a windshield replacement within 24 hrs, and received ample communication prior to Ian's arrival. Installation was flawless, and professional. Highly recommend, and I'll use Safelite again.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895132970",
    name: "Deshealeik B.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Good Windshield",
    content: "Thank you for the successful installation. Everything is in working conditions. Safelite repair; Safelite replace! Redlands Office was fast. By the time I took a seat, it was time to go.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895131846",
    name: "allie",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "windshield repair",
    content: "Zara at the front desk is great to work with. Very kind and helpful!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895131671",
    name: "Allison",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "incredible!!",
    content: "Absolutely wonderful experience from start to finish! Getting scheduled was a breeze and everyone was so kind and efficient! I would definitely recommend this business for all glass needs!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895131312",
    name: "Ted M.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Total Replacement",
    content: "Good service, inside vacuumed and all software restored to factory levls",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895131232",
    name: "TREMAINE M.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "The technician was quick and",
    content: "The technician was quick and informative",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895130360",
    name: "Thomas W.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Very pleased with the installation",
    content: "Very pleased with the installation",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895127080",
    name: "Cynthia D.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Auto glass replacement Mazda CX5 RIGHT PASSENGER WINDOW",
    content: "I had an appointment to replace the passenger rear window that was vandalized at 7am, September 22, 2026. Delores, the office administrator, scheduled me for the first available appointment.\nAlvarado greeted me and checked me in for my appointment. He explained the process to me. I told him that I had a 9:30am doctor's appointment. He said t",
    more: "hat he would do what he could to accommodate my request.\nJuan, the technician, that would ensure that the project was completed, came and checked in. My car was completed quickly and efficiently. I was able to make it to my medical appointment on time.\n\nIt was amazing to watch them set up the daily operations.\nThank you for all of the help through this stressful situation. ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895126999",
    name: "Brian H.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Just as advertised! Well done.",
    content: "Just as advertised! Well done.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895126389",
    name: "Gizelle",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Diego was the best he",
    content: "Diego was the best he did a very good job",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895123837",
    name: "Joseph V.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Safelite",
    content: "100% excellent service and offered us windshield wipers on top of new glass . Will always use their service and tell others about the service .",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895123772",
    name: "Jackie N.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "WindSheild Repair",
    content: "My experience with Safelite for my windshield repair was excellent! They communicated with me every step of the way, making the entire process easy and stress-free.\n\nMy technician was very knowledgeable, friendly, and professional. I was extremely pleased with the service I received and would highly recommend Safelite to anyone needing win",
    more: "dshield repair or replacement. ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895123610",
    name: "Linda",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "Windshield Replacement",
    content: "We needed to have there windshield replaced on our older Acura sedan when a crack appeared mysteriosly in one of the upper corners. It was easy to make the appointment. And Safelite followed up in calls, text messages and emails to make and then confirm the appointment, as well as provide updates on the appointment. Mike, the technician, got hold ",
    more: "of me to move the appointment up as he saw I'd requested have written dune in the earlier part of the window I was given for this appointment. That worked out really great for us as well as for him. The work he did was just great. The clear, clean windshield is wonderful as everything is so much clearer with much less glare from the widespread pitting in the old windshield. My receipt and links to warranty and review arrived shortly after Mike reported the work was done. We street very happy with the overall process and results. We've used Safelite before and will again should it become necessary. ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895123280",
    name: "Conrad B.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "Prompt, competent, professional",
    content: "Prompt, competent, professional",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895122124",
    name: "Jacqueline C.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "Excellent Customer Service",
    content: "The young man who came out to service my window was friendly and explained everything. Also, before he left, he asked if I had any questions. BTW, the window looked great!!",
    votesUp: 0,
    votesDown: 0,
    photo: { src: "/image/services/customer-reviews/review-photo-895122124.jpg", alt: "Image of Review by Jacqueline C. on 28 Sep 2026 number 1" },
  },
  {
    id: "895121312",
    name: "James P.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "My Tech",
    content: "My tech was amazing! On time professional, polite and very good at his craft. Safelite needs to get add the right profile picture for the tech.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895120383",
    name: "Jane W.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "Awesome job!",
    content: "The folks that recently replaced my windshield did an awesome job! Very polite and professional. They explained the whole process to me and even how to get a replacement inspection sticker. The young man sat the desk introduced me to the police officer who was able to get me a sticker and I was out of there in under 2hours! These are all great emp",
    more: "loyees! ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895117462",
    name: "Jan R.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Jorge",
    content: "Jorge was very prompt and professional . Did a great job",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895117146",
    name: "Brooke W.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "Replaced windshield",
    content: "My technician was professional and on time! Great job on replacing my broken windshield!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895116112",
    name: "Terry A.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Great Service",
    content: "What a time saver to have Dylan drive up and within a couple of hours replace my damaged windshield. I watched the process and was amazed at how the heck he got my old windshield off. After the new windshield was in place he calibrated it, another interesting process. I would recommend Safelite to anyone needing professional repairs and friendly e",
    more: "mployees. ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895115656",
    name: "Robert B.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Excellent service",
    content: "While I hate the fact that a rock from a dump truck hit my windshield, the service from safelite was excellent. The technician was on time, polite and clearly very good at what he does. The windshield is high quality, I've had issues with distortion and quality in the past, but this is clear and well installed.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895104113",
    name: "Shawna C.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "Great Service as Usual",
    content: "Chris was wonderful. Great communication before, during, and after. He is even helping us get set up with a commercial account to help save us in the future.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895099495",
    name: "Richard R.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Excellent Service",
    content: "I got a brand new 2027 Infiniti QX60, and o had a rock damage my windshield on my drive home from picking it up. My insurance allowed be to utilize Safelite for my repairs. Once the glass was shipped, I was able to get an appointment a few days later. I brought my vehicle into the shop way before my appointment time since I had work meetings on th",
    more: "e area. My vehicle was repaired and ready before my schedule appointment time. That was amazingly efficient customer service! The employees were friendly and very helpful. Very nice experience! Thank you! ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895097785",
    name: "Ginna L.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Great experience",
    content: "We had a crack in a windshield suddenly appear and grow very quickly. My husband was having surgery so my time was very restricted. Safelite came to the house, replaced the windshield, cleaned up the area and was gone in less than 2 hours. Casey was very professional, but with a great smile when we spoke. Casey also re-calibrated our back up camer",
    more: "a after the windshield was installed to make sure everything was working safely. I would definitely use them again. ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895097216",
    name: "Matthew P.",
    verified: true,
    date: "09/28/26",
    score: 5,
    title: "Great recovery",
    content: "After a few setbacks that where legitimately beyond their control, the guys at the Ft. Smith, AR location stepped up and made it right, Stayed in contact with me the whole time throughout everything and carried themselves in a way that one would come to expect from professionals",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "895097195",
    name: "Brandy H.",
    verified: false,
    date: "09/28/26",
    score: 5,
    title: "Job well done!",
    content: "We had weather the morning my windshield was being replace the repair man worked is schedule to still get me in later that day and i appreciated him trying and not making me reschedule. He did great work and windshield looks amazing.",
    votesUp: 0,
    votesDown: 0,
  },
];
