// Snapshot of the first nine pages (five reviews each) of the Yotpo reviews
// widget on safelite.com/auto-glass-services/safelite-reviews.

export type Review = {
  id: string;
  name: string;
  verified: boolean;
  // Date as the widget prints it (MM/DD/YY)
  date: string;
  score: number;
  title: string;
  // Text shown first. Line breaks are "\n".
  content: string;
  // Rest of a long review, revealed by "Read More"
  more?: string;
  votesUp: number;
  votesDown: number;
  photo?: { src: string; alt: string };
};

export const REVIEWS_PER_PAGE = 5;

// Total shown in the ratings summary
export const TOTAL_REVIEWS = 1122524;

export const REVIEWS: Review[] = [
  {
    id: "901012550",
    name: "Matt",
    verified: false,
    date: "10/02/26",
    score: 5,
    title: "Windshield Replacement",
    content: "Great work. Tech was professional and did a great job.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "901004289",
    name: "Don R.",
    verified: true,
    date: "10/02/26",
    score: 5,
    title: "Windshield replacement",
    content: "I want to recognize Safelite AutoGlass\uFFFD\uFFFD\uFFFDand particularly Matt in North Myrtle Beach and Tom in the Bluefield office\uFFFD\uFFFD\uFFFDfor going above and beyond to help me finally get my windshield replaced.\n\nMy experience actually began several months ago when I first tried to have the windshield replaced at my home in Virginia. Unfortunately, the facil",
    more: "ities servicing my area were temporarily unable to provide mobile service because the equipment needed to calibrate the windshield after installation was not operational. I decided to wait and try again later.\n\nWhen I contacted Safelite again a few months later, the service was available, but because of my travel schedule, we had difficulty finding a date that would work. I suggested that perhaps the replacement could be done while I was vacationing in South Carolina.\n\nThat is when Tom in the Bluefield office became extremely helpful. He worked to coordinate the service in North Myrtle Beach and even had a colleague verify that my insurance coverage would allow for the Toyota windshield replacement. He took ownership of the situation and helped move everything forward.\n\nOnce we arrived in North Myrtle Beach, there was another complication. The technician originally scheduled to perform the work was understandably concerned about bringing his equipment under the covered parking area because of the height clearance. We rescheduled for another day, hoping for better weather.\n\nUnfortunately, the weather became even worse.\n\nThat is when Matt became involved, and his approach to customer service was exceptional. Rather than simply rescheduling the appointment yet again, Matt looked for a way to solve the problem. He offered to come to us, pick up our vehicle, take it back to the shop where the windshield could be replaced and properly calibrated, and then return the vehicle to us when the work was completed.\n\nIt could not have worked out better.\n\nWe were able to continue enjoying our vacation without being inconvenienced, and Matt handled everything in an extremely professional manner. I felt completely comfortable entrusting the vehicle to him, and he kept what could have become a frustrating situation remarkably easy for us.\n\nThe windshield replacement appears to have been done extremely well, and everything associated with the windshield and its systems is functioning properly.\n\nWhat impressed me most throughout this experience was that both Tom and Matt were focused on finding solutions rather than simply explaining why something could not be done. Tom helped coordinate a rather unusual out-of-state arrangement, and Matt took the extra step necessary to make sure the job actually got completed despite circumstances that were beyond anyone\uFFFD\uFFFD\uFFFDs control.\n\nThat kind of customer service deserves recognition.\n\nMy sincere thanks to both Tom and Matt for their professionalism, persistence, flexibility, and willingness to go above and beyond. They turned what had been a months-long process into a very positive experience and made sure that, in the end, I was completely taken care of.\n\nI would certainly recommend Safelite AutoGlass based on the service I received from these two gentlemen. ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900983209",
    name: "Dave",
    verified: false,
    date: "10/02/26",
    score: 5,
    title: "Quick and efficient",
    content: "Jarome provided top tier service at the Lodi CA location",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900801999",
    name: "Daniel N.",
    verified: true,
    date: "10/02/26",
    score: 5,
    title: "Windshield replacement",
    content: "I scheduled an appointment to have my windshield replaced at my job while I was not there, and whe. I returned, to find the replacement job done and everything was good.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900312465",
    name: "RICHARD P.",
    verified: false,
    date: "10/02/26",
    score: 5,
    title: "very professionand friendly",
    content: "very professionand friendly",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900310525",
    name: "LaMorris",
    verified: true,
    date: "10/02/26",
    score: 4,
    title: "Excellent service!",
    content: "My new windshield was so cost appropriate.\nI got the best price and quality at Safelite.\nGreat customer service from everyone!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900310371",
    name: "Jaxson B.",
    verified: false,
    date: "10/02/26",
    score: 5,
    title: "Quality Service",
    content: "The technician, Adam, who came out to my house to replace my windshield was personable and professional. He gave me an extremely accurate time estimate and the windshield looks great. Highly recommend",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900306668",
    name: "Paul j.",
    verified: true,
    date: "10/02/26",
    score: 5,
    title: "Windshield replacement",
    content: "I was very satisfied with the timely service. My installer was very courteous and professional.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900300283",
    name: "Elizabeth N.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Window replacement",
    content: "Top notch service for my window replacement. Customer service, reminder calls and technician were awesome!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900297818",
    name: "Ryan J.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Fast and professional",
    content: "Took them under an hour after I dropped it off walked me through all of the aftercare steps and there are no leaks. I'll happily do business with Safelite in the future.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900290898",
    name: "R S.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Landcruiser",
    content: "The tech did a great job, was very thorough and professional. We have seen no issues",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900289344",
    name: "Sandra W.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Thanks, Safelite!",
    content: "Came out on time and replaced our cracked windshield as promised. It looks great!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900284872",
    name: "Jessica J.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Glass repair",
    content: "Very great service!! Kept things cleaned and done quickly. I’m very impressed with his work!! Steven did so great!!!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900284656",
    name: "Thelma N.",
    verified: false,
    date: "10/01/26",
    score: 5,
    title: "Windshield.",
    content: "They did a wonderful job and they explained everything. I highly recommend Safelite to everyone. Thank you Safelite!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900279651",
    name: "Patrice T.",
    verified: false,
    date: "10/01/26",
    score: 5,
    title: "Great Job, John!",
    content: "When something hit my window and the 5in crack grew to over 15in in a couple f days, we were really nervous. The car’s older and my dealer didn’t have replacement glass. But SafeLite came to the rescue. They worked with my insurance company, made sure the right glass was available, and scheduled an appointment at my home the next day! The technici",
    more: "an, John, let me know when to expect him and arrived just as planned. He did a fabulous job, quickly and very professionally. He was very knowledgeable and made sure to tell me everything I needed to know.\n\nI would definitely use them again! ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900268111",
    name: "John",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Knowledgeable and courteous installer. Very",
    content: "Knowledgeable and courteous installer. Very Pleased.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900265203",
    name: "K. W.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "1990 BMW Windshield Replacement",
    content: "I am extremely pleased with the work the folks at Safelite in Acton MA did replacing my car's windshield. The process was very simple and straightforward. The workmanship was great and the turnaround time was about 2 hours. And the people were very friendly too! Great job! Thank you.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900259329",
    name: "Shirley y.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "The tech that came was",
    content: "The tech that came was Justin. He was very friendly and professional. He was quick. Thanks Justin for your awesome work.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900252991",
    name: "Brie",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Great experience",
    content: "I was out of state on the Labor Day weekend when a large branch fell and shattered my windshield. The process went very smoothly. The office staff were very helpful, efficient, friendly and professional. The technician was also very experienced and thorough replacing the windshield. This stressful situation for me couldn’t have gone any better!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900242001",
    name: "Linda",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Excellent service replacing my windshield",
    content: "Rock from a car hit my left side of the RAV4 2014 windshield and made a hole and large crack. Hate that. I had an 11 AM appointment, and they called earlier in the morning to let me know the tech was sick — but they still kept everything on schedule. The shop was clean and organized, and they finished the windshield replacement in about 45 minutes",
    more: ". The insurance company covered the work, and the whole process was quick and hassle‑free. Great communication and great service. Highly recommend. ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900241803",
    name: "Gabriel S.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Excellent service and work from",
    content: "Excellent service and work from the company and its collaborator Taylor.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900198824",
    name: "Laurie T.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Outstanding service",
    content: "From start to finish Safelite in Franklin was incredible. Super professional. They put together and installed my clunky broken interior rear view mirror, went above and beyond and even attached my loose ezpass onto the windshield. I was so happy ☺️",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900196859",
    name: "Shelly",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "I'm very happy with my",
    content: "I'm very happy with my windshield replacement. I definitely recommend Safelite!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900192037",
    name: "Russell H.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Great service every time",
    content: "I have used Safelite AutoGlass here in Simpsonville several times and they have been great to work with every time. They are responsive, always on time, professional, and go above and beyond to make sure the experience is as smooth as possible. I would highly recommend them here in Simpsonville to anybody.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900186985",
    name: "Keith",
    verified: false,
    date: "10/01/26",
    score: 5,
    title: "Quality & efficiency",
    content: "A very careful worker came to my driveway an a big red van and methodically removed the old broken window and prepped the opening carefully and used the most duper glue gun you’ve ever seen to put sealer on the window and install it on the car.\nThe mirror and toll road machine and even the repair shop I’d sticker from the corner of the window ",
    more: "were all replaced to the new window, positioned perfectly. ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900174973",
    name: "mike",
    verified: false,
    date: "10/01/26",
    score: 5,
    title: "front windshield 2023 bronco sport",
    content: "were on time-recalibrated all good at my house",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900173280",
    name: "Jim R.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Great service",
    content: "Safelite replaced both of our windshields quickly and professionally. Scheduling was simple, and the technician came to our home and completed the work efficiently. The entire process was convenient and stress-free, with great service from beginning to end.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "900145281",
    name: "Don J.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Always right the First time",
    content: "I own a Toyota FJ Cruiser so I’m\nOn my 4 th windshield. It does take almost 3 hours to get it replaced but it’s done right the first time I’ve NEVER. Had to go back because of wind noise or not a secure placement. And trust me it has happened. So they do a great job the first time you go in for a replacement. But if going 4 times is because ro",
    more: "cks and road debris are not friendly to a Toyota FJ Cruiser. ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898320294",
    name: "John S.",
    verified: false,
    date: "10/01/26",
    score: 5,
    title: "Great Service",
    content: "Had my windshield replaced with high quality, etc. in less than 2 hrs. at my house.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898317890",
    name: "Dixie",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "AMAZING",
    content: "My experience with Safelite was AMAZING. He was on time. It took a little over an hour. No problems at all.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898315795",
    name: "Sheri B.",
    verified: false,
    date: "10/01/26",
    score: 5,
    title: "My Broken Windshield",
    content: "I have dealt with Safelite before and received excellent service before. My service technician Enrique exceeded my expectations. He arrived earlier then expected and was very friendly, honest and up front about what to expect.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898315224",
    name: "Collin W.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Very Pleased",
    content: "The gentleman that came out to fix my windshield was very knowledgable and answered all my questions confidently. Will use Safelite again for any windshield or glass issues.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898314505",
    name: "Sheila M.",
    verified: true,
    date: "10/01/26",
    score: 5,
    title: "Great group of people",
    content: "Austin at the front desk was super efficient and pleasant to work with. Everyone involved in the replacement (Jon Trawick) and recalibration of my windshield were just as top notch. The service was great and the wait time was less than expected. Thank you.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898313586",
    name: "Rose C.",
    verified: false,
    date: "10/01/26",
    score: 5,
    title: "Windshield replacement and recalibration",
    content: "Windshield replacement and recalibration",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898312581",
    name: "Brian M.",
    verified: true,
    date: "09/30/26",
    score: 5,
    title: "Easy process",
    content: "We were on a road trip and our windshield was hit and it cracked by a rock from a passing truck. We had it replaced within three days, our technician came to us and did a fantastic job. He was very friendly and efficient and professional. Highly recommend!",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898310205",
    name: "Sierra J.",
    verified: true,
    date: "09/30/26",
    score: 5,
    title: "Efficient",
    content: "Quick and easy replacement of my windshield. I waited at the shop, was greeted when I walked in and I was out within an hour. Great service and I am happy I was able to use them",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898309929",
    name: "Jean B.",
    verified: true,
    date: "09/30/26",
    score: 5,
    title: "Full Windshield Replaced",
    content: "The tech came to the apartment and before he arrived, he texted me through out the day, last text said \"20 mins. away\". This was very helpful. He did an excellent job on replacement. Left me all the information I might need in the future.... Very Nice tech.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898309006",
    name: "Melvin S.",
    verified: true,
    date: "09/30/26",
    score: 5,
    title: "First time",
    content: "I have a 2005 SUV and went to Safelite Auto Glass to get the windshield replaced they did a wonderful job I paid for the premium service but instead of just taking good wiper blades off my truck they refunded me the money back I like that kind of honesty because I spent a lot of money on the wiper blades that's on it they did a quality job on the ",
    more: "windshield just wished that I could of went back and had the rain repellent put on the window I guess they couldn't put it on because it was raining that day but they refunded me the money I have an appointment for next Saturday to get the windshield in my 2005 Pontiac replaced I got a excellent price on both windshields ",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898307645",
    name: "Cynthia",
    verified: true,
    date: "09/30/26",
    score: 5,
    title: "Windshield replace",
    content: "George with Safelite was efficient and friendly. Safelite is a very efficient company.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898306388",
    name: "Ycastaneda",
    verified: true,
    date: "09/30/26",
    score: 5,
    title: "Amazing",
    content: "The best glass replacement established I have experience with my insurance. The tech are respectful and great customer service.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898303291",
    name: "Miranda H.",
    verified: true,
    date: "09/30/26",
    score: 5,
    title: "Windshield replacement",
    content: "Extremely kind and got the work done faster than expcted.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898303255",
    name: "Karen H.",
    verified: false,
    date: "09/30/26",
    score: 5,
    title: "Wonderful Experience",
    content: "No one likes to have to have their windshield replaced. But if you need to have it done Safelite in Murfreesboro, TN is the place to go. It was easy to set up an appointment that suited my schedule (a Saturday appointment). The staff were extremely courteous. And my car was done quickly.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898303040",
    name: "Roger J.",
    verified: true,
    date: "09/30/26",
    score: 5,
    title: "99 Dakota",
    content: "I want to thank you and your tech for coming out to Cliff's shop where my Dakota was and replacing my windshield. I believe it was raining and the shop made room to place my truck in one of their bays so the glass tech could do his job.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898303008",
    name: "E F.",
    verified: true,
    date: "09/30/26",
    score: 5,
    title: "Great Job",
    content: "Excellent job with Satellite replacing my car's front windshield. No complaints. Perfect fit and easy service at my home.",
    votesUp: 0,
    votesDown: 0,
  },
  {
    id: "898302869",
    name: "Courtney A.",
    verified: false,
    date: "09/30/26",
    score: 5,
    title: "AWESOME SERVICE!",
    content: "Super easy and quick, and my tech, Elbert, was great. He came to my home, gave me an estimate on time, and then was done early with replacing my windshield. Really appreciated him!",
    votesUp: 0,
    votesDown: 0,
  },
];
