// Safelite stores by state, in the order shown on the reference page.
// Each store: [page, city, street address]
export type StoreLink = [href: string, city: string, address: string];

export type StateLocations = {
  name: string;
  // "View <state> locations" page
  href: string;
  stores: StoreLink[];
};

export const STATE_LOCATIONS: StateLocations[] = [
  {
    name: "Alabama",
    href: "/locations/state/alabama",
    stores: [
      ["/stores/birmingham", "Birmingham", "208 Oxmoor Ct"],
      ["/stores/dothan", "Dothan", "3765 Ross Clark Cir"],
      ["/stores/hoover-al", "Hoover", "3420 Galleria Circle"],
      ["/stores/madison-al", "Madison", "8755 Madison Blvd"],
      ["/stores/mobile-al", "Mobile", "1224 Montlimar Drive"],
      ["/stores/montgomery", "Montgomery", "116 Eastdale Rd S"],
      ["/stores/oxford", "Oxford", "1706 Hillyer Robinson Pky"],
      ["/stores/scottsboro-al", "Scottsboro", "2902 Veterans Dr"],
      ["/stores/foley-mobile-auto-glass", "Summerdale", "105 County Road 32 W"],
      ["/stores/tuscaloosa", "Tuscaloosa", "2525 Mcfarland Blvd E"],
    ],
  },
  {
    name: "Alaska",
    href: "/locations/state/alaska",
    stores: [
      ["/stores/anchorage-northern-lights", "Anchorage", "1650 W Northern Lights"],
      ["/stores/fairbanks", "Fairbanks", "975 Van Horn Rd"],
      ["/stores/wasilla", "Wasilla", "1265 S Seward Meridian Rd"],
    ],
  },
  {
    name: "Arizona",
    href: "/locations/state/arizona",
    stores: [
      ["/stores/avondale", "Avondale", "1595 N 113Th Ave"],
      ["/stores/buckeye-az", "Buckeye", "945 N 215Th Ave"],
      ["/stores/bullhead-city-mobile-auto-glass", "Bullhead City", "2200 Rancho Colorado Blvd"],
      ["/stores/cottonwood-mobile-auto-glass", "Camp Verde", "550 N Industrial Dr"],
      ["/stores/casa-grande-az", "Casa Grande", "1715 N Pinal Ave"],
      ["/stores/chandler-az", "Chandler", "6625 West Chandler Blvd"],
      ["/stores/chandler", "Chandler", "2060 N Arizona Ave"],
      ["/stores/eagar", "Eagar", "520 N Main Street"],
      ["/stores/flagstaff", "Flagstaff", "2421 N 4Th St"],
      ["/stores/mesa-arizona", "Gilbert", "4320 E Warner Rd"],
      ["/stores/kingman-mobile-auto-glass", "Kingman", "4165 1/2 N Bank St"],
      ["/stores/lake-havasu", "Lake Havasu City", "1884 Acoma Blvd W"],
      ["/stores/mesa-east-mckellips-rd", "Mesa", "5851 E Mckellips Rd"],
      ["/stores/payson-mobile-auto-glass", "Payson", "434 S Beeline Hwy"],
      ["/stores/peoria", "Peoria", "18783 N 83Rd Ave"],
      ["/stores/north-phoenix", "Phoenix", "23610 N 20Th Dr"],
      ["/stores/prescott", "Prescott", "741 N Montezuma St"],
      ["/stores/queen-creek", "Queen Creek", "22325 S Scotland Court"],
      ["/stores/scottsdale", "Scottsdale", "8175 E Raintree Dr"],
      ["/stores/show-low", "Show Low", "1590 S White Mountain Rd"],
      ["/stores/sierra-vista", "Sierra Vista", "4148 Industry Dr"],
      ["/stores/surprise", "Surprise", "11180 N. Dysart Road"],
      ["/stores/taylor-az", "Taylor", "502 N Main Street"],
      ["/stores/tempe-az", "Tempe", "2405 W University Dr"],
      ["/stores/tucson-ina", "Tucson", "3571 W Ina Rd"],
      ["/stores/tuscon-az", "Tucson", "6401 S Country Club Rd"],
      ["/stores/tucson-s-kolb", "Tucson", "1402 S Kolb Rd"],
      ["/stores/yuma", "Yuma", "260 W 23Rd St"],
    ],
  },
  {
    name: "Arkansas",
    href: "/locations/state/arkansas",
    stores: [
      ["/stores/bentonville-ar", "Bentonville", "310 North Walton Blvd."],
      ["/stores/conway", "Conway", "900 Runway Ave"],
      ["/stores/fayetteville", "Fayetteville", "611 N College Ave"],
      ["/stores/ft-smith", "Fort Smith", "4300 Rogers Ave"],
      ["/stores/jonesboro-mobile-auto-glass", "Jonesboro", "3223 Neil Cir"],
      ["/stores/little-rock", "Little Rock", "1306 S University Ave"],
      ["/stores/magnolia-ar", "Magnolia", "329 Legion Dr"],
      ["/stores/springdale", "Springdale", "3546 W Sunset Ave"],
    ],
  },
  {
    name: "California",
    href: "/locations/state/california",
    stores: [
      ["/stores/auburn-ca", "Auburn", "4065 Grass Valley Hwy"],
      ["/stores/bakersfield", "Bakersfield", "3208 Pegasus Dr"],
      ["/stores/bakersfield-ca", "Bakersfield", "3101 N Sillect Ave"],
      ["/stores/brentwood-ca", "Brentwood", "6818 Lone Tree Way"],
      ["/stores/camarillo", "Camarillo", "3316 Maya Linda"],
      ["/stores/carlsbad-ca", "Carlsbad", "5205 Avenida Encinas"],
      ["/stores/chico-esplanade-ca", "Chico", "2819 Esplanade"],
      ["/stores/chula-vista", "Chula Vista", "1415 Broadway"],
      ["/stores/concord", "Concord", "2655 Monument Blvd"],
      ["/stores/corona-ca", "Corona", "6 Latitude Way Suite 108"],
      ["/stores/covina", "Covina", "576 N Citrus Ave"],
      ["/stores/dublin-ca", "Dublin", "6841 Dublin Blvd."],
      ["/stores/el-cajon", "El Cajon", "1243 Greenfield Dr"],
      ["/stores/escondido", "Escondido", "2750 Auto Park Way"],
      ["/stores/fairfield", "Fairfield", "4670 Central Way"],
      ["/stores/fresno", "Fresno", "1225 North Clovis Ave"],
      ["/stores/fullerton-ca", "Fullerton", "1020 E Elm Ave"],
      ["/stores/gardena", "Gardena", "16422 S Avalon Blvd"],
      ["/stores/inglewood-ca", "Inglewood", "10223-10225 S Praire Ave"],
      ["/stores/irvine", "Irvine", "3 Faraday"],
      ["/stores/lancaster-ca", "Lancaster", "43403 10Th St W"],
      ["/stores/lodi-ca", "Lodi", "1110 S Cherokee Ln"],
      ["/stores/long-beach-ca", "Long Beach", "1440 W Pacific Coast Hwy"],
      ["/stores/los-angeles-ca-east-la-cienega", "Los Angeles", "1788 S La Cienega Blvd"],
      ["/stores/modesto", "Modesto", "5033 Pentecost Dr"],
      ["/stores/murrieta", "Murrieta", "26175 Jefferson Ave"],
      ["/stores/oakland", "Oakland", "4238 Broadway"],
      ["/stores/palm-springs", "Palm Springs", "3700 E Tachevah Dr"],
      ["/stores/pasadena", "Pasadena", "1393 E Walnut St"],
      ["/stores/placerville", "Placerville", "131 Placerville Dr"],
      ["/stores/rancho-cordova", "Rancho Cordova", "11349 Folsom Blvd"],
      ["/stores/rancho-cucamonga-masi", "Rancho Cucamonga", "8160 Masi Dr"],
      ["/stores/redding-ca-bechelli", "Redding", "2820 Bechelli Ln"],
      ["/stores/redlands", "Redlands", "560 Nevada St."],
      ["/stores/reseda-ca", "Reseda", "18051 Sherman Way"],
      ["/stores/riverside", "Riverside", "3197 Motor Cir"],
      ["/stores/roseville", "Rocklin", "5800 Pacific St"],
      ["/stores/sacramento-ca", "Sacramento", "4701 Florin Rd"],
      ["/stores/salinas", "Salinas", "1276 Abbott St"],
      ["/stores/san-diego", "San Diego", "7880 Dunbrook Rd"],
      ["/stores/san-francisco", "San Francisco", "1680 Evans Ave"],
      ["/stores/san-jose-ca", "San Jose", "545 Parrott St"],
      ["/stores/san-mateo", "San Mateo", "1011 South Claremont St."],
      ["/stores/san-rafael", "San Rafael", "95 Louise St"],
      ["/stores/santa-barbara-ca", "Santa Barbara", "526 Anacapa St"],
      ["/stores/santa-clara", "Santa Clara", "2555 Lafayette St"],
      ["/stores/santa-cruz", "Santa Cruz", "1709 Soquel Ave"],
      ["/stores/santa-maria", "Santa Maria", "2220 A St"],
      ["/stores/santa-rosa", "Santa Rosa", "3355 Mcmaude Place"],
      ["/stores/south-san-francisco", "South San Francisco", "955 Airport Blvd"],
      ["/stores/stockton-ca", "Stockton", "345 N Wilson Way"],
      ["/stores/van-nuys", "Sun Valley", "11063 Pendleton St"],
      ["/stores/turlock", "Turlock", "551 S Center St"],
      ["/stores/union-city", "Union City", "33432 Central Ave"],
      ["/stores/victorville", "Victorville", "15375 Anacapa Rd"],
      ["/stores/visalia", "Visalia", "225 S Cotta Ct"],
      ["/stores/sacramento", "West Sacramento", "3065 Ramco Street"],
      ["/stores/westminster", "Westminster", "7501 Suzi Ln"],
      ["/stores/yuba-city", "Yuba City", "960 Gray Ave"],
    ],
  },
  {
    name: "Colorado",
    href: "/locations/state/colorado",
    stores: [
      ["/stores/arvada", "Arvada", "7985 Allison Way"],
      ["/stores/aurora", "Aurora", "4313 S Buckley Rd"],
      ["/stores/aurora-fraser", "Aurora", "3254 Fraser St"],
      ["/stores/boulder", "Boulder", "2480 30Th St"],
      ["/stores/castle-rock", "Castle Rock", "1133 Caprice Drive"],
      ["/stores/colorado-springs", "Colorado Springs", "6245 N Academy Blvd"],
      ["/stores/colorado-springs-co", "Colorado Springs", "5850 Championship Vw"],
      ["/stores/colorado-springs-south", "Colorado Springs", "4825 Centennial Blvd"],
      ["/stores/colorado-springs-widefield", "Colorado Springs", "1902 Aerotech Drive"],
      ["/stores/cortez-co", "Cortez", "448 West Main Street"],
      ["/stores/central-denver", "Denver", "4055 E Evans Ave"],
      ["/stores/sw-lakewood", "Denver", "7880 W Quincy Ave"],
      ["/stores/durango-co", "Durango", "408 East 8Th Avenue"],
      ["/stores/ft-collins", "Fort Collins", "101 W Monroe Dr"],
      ["/stores/fort-morgan-co", "Fort Morgan", "16308 County Rd 19"],
      ["/stores/frisco", "Frisco", "757 Ten Mile Dr"],
      ["/stores/glenwood-springs", "Glenwood Springs", "1838 Grand Ave"],
      ["/stores/grand-junction", "Grand Junction", "610 Foresight Cir E"],
      ["/stores/greeley", "Greeley", "2502 W 10Th St"],
      ["/stores/highlands-ranch", "Highlands Ranch", "5701 County Line Pl"],
      ["/stores/lakewood", "Lakewood", "100 Wadsworth Blvd"],
      ["/stores/longmont", "Longmont", "1940 Main St"],
      ["/stores/loveland2", "Loveland", "3716 Aldrin Dr"],
      ["/stores/pagosa-springs-co", "Pagosa Springs", "2115 Eagle Drive"],
      ["/stores/parker-co", "Parker", "18632 Pony Express Dr"],
      ["/stores/pueblo", "Pueblo", "1406 W Us Highway 50"],
      ["/stores/thornton", "Thornton", "2571 E 120Th Ave"],
    ],
  },
  {
    name: "Connecticut",
    href: "/locations/state/connecticut",
    stores: [
      ["/stores/bridgeport", "Bridgeport", "292 North Ave"],
      ["/stores/danbury", "Danbury", "32 Tamarack Ave"],
      ["/stores/east-hartford", "Manchester", "21 Tolland Tpke"],
      ["/stores/niantic-ct", "Niantic", "15 Industrial Park Rd"],
      ["/stores/north-haven", "North Haven", "459 Washington Ave"],
      ["/stores/stamford", "Stamford", "1447 Summer St"],
      ["/stores/stratford-ct", "Stratford", "55 Lupes Dr"],
      ["/stores/waterbury", "Waterbury", "40 Industry Ln"],
      ["/stores/west-hartford", "West Hartford", "226 South St"],
    ],
  },
  {
    name: "Delaware",
    href: "/locations/state/delaware",
    stores: [
      ["/stores/dover", "Dover", "4200 N Dupont Hwy"],
      ["/stores/georgetown", "Georgetown", "22834 Dupont Blvd"],
      ["/stores/wilmington", "Wilmington", "4722 Kirkwood Hwy"],
    ],
  },
  {
    name: "Florida",
    href: "/locations/state/florida",
    stores: [
      ["/stores/altamonte-springs", "Altamonte Springs", "1136 E Altamonte Dr"],
      ["/stores/apollo-beach", "Apollo Beach", "5469 North Us Highway 41"],
      ["/stores/apopka-fl", "Apopka", "1440 E. Semoran Blvd"],
      ["/stores/brooksville", "Brooksville", "12153 Cortez Blvd"],
      ["/stores/capecoral-fl", "Cape Coral", "1028 Del Prado Blvd South"],
      ["/stores/crestview-mobile-auto-glass", "Crestview", "100 Lloyd Street N"],
      ["/stores/daytona-beach", "Daytona Beach", "1550 N Nova Rd"],
      ["/stores/ft-myers", "Fort Myers", "3733 Fowler St"],
      ["/stores/fort-walton-beach", "Fort Walton Beach", "123 Hollywood Blvd Ne"],
      ["/stores/gainesville", "Gainesville", "2525 N Main St"],
      ["/stores/homestad-fl", "Homestead", "30000 S Dixie Hwy"],
      ["/stores/jacksonville", "Jacksonville", "7014 A C Skinner Pkwy"],
      ["/stores/jacksonville-fl", "Jacksonville", "2628 Port Industrial Dr"],
      ["/stores/kissimmee", "Kissimmee", "604 E Osceola Pkwy"],
      ["/stores/lakeland", "Lakeland", "2315 Commerce Point Dr"],
      ["/stores/largo-st-petersburg", "Largo", "12580 71St Ct"],
      ["/stores/leesburg", "Leesburg", "1720 Leesburg Commons Ct"],
      ["/stores/melbourne", "Melbourne", "4180 W New Haven Ave"],
      ["/stores/dade", "Miami", "2757 Sw 8Th St"],
      ["/stores/midway", "Midway", "1205 Commerce Blvd"],
      ["/stores/clermont-mobile-auto-glass", "Minneola", "902 Jan Mar Ct"],
      ["/stores/naples-mobile-auto-glass", "Naples", "16000 Old 41 N"],
      ["/stores/fort-lauderdale", "Oakland Park", "555 E Oakland Park Blvd"],
      ["/stores/ocala", "Ocala", "925 Nw 6Th Ter"],
      ["/stores/orange-park", "Orange Park", "1415 Kingsley Ave"],
      ["/stores/orlando", "Orlando", "3122 Shader Rd"],
      ["/stores/azalea-park", "Orlando", "6761 Curtis Street"],
      ["/stores/palm-harbor", "Palm Harbor", "30950 Us Highway 19 N"],
      ["/stores/palmetto-fl", "Palmetto", "1800 14Th Avenue East"],
      ["/stores/panama-city-frankford", "Panama City", "1415 Frankford Ave"],
      ["/stores/pembroke-park", "Pembroke Park", "3205 Sw 22Nd St"],
      ["/stores/pensacola", "Pensacola", "351 Creighton Rd"],
      ["/stores/port-charlotte", "Port Charlotte", "1182 Tamiami Trl"],
      ["/stores/port-saint-lucie-mobile-auto-glass", "Port Saint Lucie", "182 Sw Port St Lucie Blvd"],
      ["/stores/st-augustine-fl", "Saint Augustine", "70 Dobbs Business Circle, Unit 401"],
      ["/stores/sanford", "Sanford", "1021 Monroe Road"],
      ["/stores/sarasota", "Sarasota", "1509 N Washington Blvd"],
      ["/stores/tampa", "Tampa", "4214 N Armenia Ave"],
      ["/stores/tampa-adamo", "Tampa", "9017 E Adamo Dr"],
      ["/stores/tampa-fl", "Tampa", "6408 W Linebaugh Ave"],
      ["/stores/lake-city-mobile-auto-glass", "Thonotosassa", "11451 N. Us Hwy 301"],
      ["/stores/west-palm-beach", "West Palm Beach", "924 N Military Trl"],
    ],
  },
  {
    name: "Georgia",
    href: "/locations/state/georgia",
    stores: [
      ["/stores/albany-mobile-auto-glass", "Albany", "2220 Gillionville Rd"],
      ["/stores/alpharetta-ga", "Alpharetta", "12940 Ga-9"],
      ["/stores/athens-mobile-auto-glass", "Athens", "1040 Highway 29 N"],
      ["/stores/brunswick-ga", "Brunswick", "700 Mall Blvd"],
      ["/stores/buford", "Buford", "1739 Buford Hwy Ne"],
      ["/stores/cartersville", "Cartersville", "40 S Morningside Dr"],
      ["/stores/columbus-ga", "Columbus", "7800 Veterans Pkwy"],
      ["/stores/conyers", "Conyers", "1521 Dogwood Dr Sw"],
      ["/stores/cumming", "Cumming", "3427 Keith Bridge Rd"],
      ["/stores/dalton-ga", "Dalton", "306 W Walnut Ave"],
      ["/stores/lilburn-ga", "Lilburn", "621C Indian Trail Lilburn Rd Nw"],
      ["/stores/lithia-springs", "Lithia Springs", "420 Thornton Rd"],
      ["/stores/macon", "Macon", "2029 Oglesby Place"],
      ["/stores/marietta", "Marietta", "1011 S Marietta Pkwy Se"],
      ["/stores/marietta-ga", "Marietta", "1157 S. Marietta Pkwy Se"],
      ["/stores/martinez", "Martinez", "4070 Washington Rd"],
      ["/stores/pooler", "Pooler", "1370 Us Highway 80 E"],
      ["/stores/union-city-ga", "Union City", "6730 Oakley Industrial"],
      ["/stores/valdosta-mobile-auto-glass", "Valdosta", "2295 Us Highway 84 W"],
    ],
  },
  {
    name: "Hawaii",
    href: "/locations/state/hawaii",
    stores: [
      ["/stores/manono-hi", "Hilo", "1133 Manono Street #9"],
      ["/stores/honolulu", "Honolulu", "2815 Koapaka St"],
      ["/stores/kahului-mobile-auto-glass", "Kahului", "60 E Wakea Ave"],
    ],
  },
  {
    name: "Idaho",
    href: "/locations/state/idaho",
    stores: [
      ["/stores/boise-overland", "Boise", "6310 W Overland Rd"],
      ["/stores/boise-id-steelhead", "Boise", "445 N Steelhead Way"],
      ["/stores/boise", "Boise", "11575 W President Dr"],
      ["/stores/nampa", "Caldwell", "4522 Cleveland Blvd"],
      ["/stores/coeur-d-alene", "Coeur D Alene", "235 W Dalton Ave"],
      ["/stores/garden-city-id", "Garden City", "3933 West Chinden Blvd"],
      ["/stores/idaho-falls", "Idaho Falls", "1130 E 17Th St"],
      ["/stores/lewiston-mobile-auto-glass", "Lewiston", "504 24Th St N"],
      ["/stores/pocatello", "Pocatello", "1120 Yellowstone Ave"],
      ["/stores/star-id", "Star", "10366 W State St"],
      ["/stores/twin-falls", "Twin Falls", "1301 Kimberly Rd"],
    ],
  },
  {
    name: "Illinois",
    href: "/locations/state/illinois",
    stores: [
      ["/stores/addison-il", "Addison", "1450 W Fullerton Ave"],
      ["/stores/alton", "Alton", "320 Homer M Adams Pkwy"],
      ["/stores/berwyn", "Berwyn", "6538 Ogden Ave"],
      ["/stores/bloomington", "Bloomington", "601 E Locust St"],
      ["/stores/carbondale", "Carbondale", "701 W Industrial Park Rd"],
      ["/stores/champaign", "Champaign", "719 S Neil St"],
      ["/stores/chicago-whubbard", "Chicago", "1945 W Hubbard St"],
      ["/stores/crest-hill", "Crest Hill", "2406 Plainfield Rd"],
      ["/stores/decatur-il", "Decatur", "1303 N Main St"],
      ["/stores/elgin", "Elgin", "555 N Mclean Blvd"],
      ["/stores/fairview-hts", "Fairview Heights", "9998 Saint Clair Ave"],
      ["/stores/jacksonville-il-mobile-auto-glass", "Jacksonville", "817 E Morton Ave"],
      ["/stores/lake-in-the-hills-il", "Lake In The Hills", "1070 W Algonquin Rd"],
      ["/stores/mattoon-mobile-auto-glass", "Mattoon", "800 N Route 45"],
      ["/stores/moline", "Moline", "2829 Avenue Of The Cities"],
      ["/stores/morton-grove", "Morton Grove", "8910 Waukegan Rd"],
      ["/stores/mundelein", "Mundelein", "325 Townline Rd"],
      ["/stores/naperville", "Naperville", "1580 W Ogden Ave"],
      ["/stores/oak-lawn", "Oak Lawn", "9609 Southwest Hwy"],
      ["/stores/peoria-il", "Peoria", "2530 W Lake Ave"],
      ["/stores/peru", "Peru", "3805 Progress Blvd"],
      ["/stores/quincy-il", "Quincy", "2925 Wisman Ln"],
      ["/stores/rockford", "Rockford", "1803 E Riverside Blvd"],
      ["/stores/south-holland", "South Holland", "668 E 162Nd St"],
      ["/stores/springfield-il", "Springfield", "3316 Robbins Rd"],
      ["/stores/wood-dale", "Wood Dale", "950 N Il-83"],
    ],
  },
  {
    name: "Indiana",
    href: "/locations/state/indiana",
    stores: [
      ["/stores/anderson-mobile-auto-glass", "Anderson", "2808 Dr. Mlk Blvd"],
      ["/stores/bloomington-in", "Bloomington", "2621 N Walnut St"],
      ["/stores/henderson", "Evansville", "1334 N Green River Rd"],
      ["/stores/fort-wayne", "Fort Wayne", "6011 Highview Dr"],
      ["/stores/indianapolis", "Indianapolis", "4625 W 86Th St"],
      ["/stores/indianapolis-shadeland", "Indianapolis", "940 N Shadeland Ave"],
      ["/stores/lafayette-in", "Lafayette", "3480 Kossuth St"],
      ["/stores/mishawaka", "Mishawaka", "4030 N Home St"],
      ["/stores/muncie", "Muncie", "1550 E Mcgalliard Rd"],
      ["/stores/terre-haute", "Terre Haute", "515 W Honey Creek Dr"],
    ],
  },
  {
    name: "Iowa",
    href: "/locations/state/iowa",
    stores: [
      ["/stores/ames", "Ames", "816 S Duff Ave"],
      ["/stores/burlington-mobile-auto-glass", "Burlington", "2530 Mount Pleasant St"],
      ["/stores/cedar-rapids", "Cedar Rapids", "425 8Th Ave Se"],
      ["/stores/clive", "Clive", "8580 Hickman Rd"],
      ["/stores/davenport", "Davenport", "409 W 76Th St"],
      ["/stores/dubuque", "Dubuque", "2828 University Ave"],
      ["/stores/fort-dodge", "Fort Dodge", "925 S 22Nd St"],
      ["/stores/grimes", "Grimes", "1300 Se Gateway Dr"],
      ["/stores/iowa-city", "Iowa City", "547 Southgate Ave"],
      ["/stores/marshalltown", "Marshalltown", "201 Market St"],
      ["/stores/ottumwa", "Ottumwa", "614 E Main St"],
      ["/stores/sioux-city", "Sioux City", "815 W 8Th St"],
      ["/stores/spencer-ia", "Spencer", "1014 11Th St Sw"],
      ["/stores/waterloo", "Waterloo", "1321 Ansborough Ave"],
    ],
  },
  {
    name: "Kansas",
    href: "/locations/state/kansas",
    stores: [
      ["/stores/dodge-city-ks", "Dodge City", "804 Beeson Ct Unit 18"],
      ["/stores/hutchinson", "Hutchinson", "1700 N Plum St"],
      ["/stores/manhattan-ks", "Manhattan", "1019 Hostetler Dr"],
      ["/stores/olathe", "Olathe", "16500 W 118Th Ter"],
      ["/stores/salina-n-oh-ks", "Salina", "333 N Ohio St"],
      ["/stores/overland-park", "Shawnee", "10306 Shawnee Mission Pky"],
      ["/stores/topeka", "Topeka", "400 Se 10Th Ave"],
      ["/stores/wichita", "Wichita", "8805 E 34Th St N"],
    ],
  },
  {
    name: "Kentucky",
    href: "/locations/state/kentucky",
    stores: [
      ["/stores/bowling-green", "Bowling Green", "2508 Scottsville Rd"],
      ["/stores/elizabethtown", "Elizabethtown", "2408 Ring Rd"],
      ["/stores/florence", "Florence", "1041 Burlington Pike"],
      ["/stores/hopkinsville", "Hopkinsville", "2108 Fort Campbell Blvd"],
      ["/stores/lexington", "Lexington", "1088 E New Circle Rd"],
      ["/stores/london", "London", "1233 S Main St"],
      ["/stores/louisville", "Louisville", "2271 Stanley Gault Pkwy"],
      ["/stores/paducah", "Paducah", "201 S 6Th St"],
    ],
  },
  {
    name: "Louisiana",
    href: "/locations/state/louisiana",
    stores: [
      ["/stores/alexandria-la", "Alexandria", "2080 N Macarthur Dr"],
      ["/stores/baton-rouge", "Baton Rouge", "7155 Exchequer Dr"],
      ["/stores/hammond-mobile-auto-glass", "Hammond", "1010 C M Fagan Dr"],
      ["/stores/harvey", "Harvey", "2000 Lapalco Blvd"],
      ["/stores/houma", "Houma", "1064 W Tunnel Blvd"],
      ["/stores/kenner-la", "Kenner", "2235 Veterans Memorial Blvd"],
      ["/stores/mandeville", "Mandeville", "2424 N Causeway Blvd"],
      ["/stores/scott", "Scott", "207 Harold Gauthe Rd"],
      ["/stores/professional-drive-la", "Shreveport", "741 Professional Dr N"],
      ["/stores/slidell-la", "Slidell", "56705 Garrett Road"],
      ["/stores/sulphur-la", "Sulphur", "3405 Maplewood Dr"],
      ["/stores/walker-la", "Walker", "9165 Comar Drive, Ste C"],
      ["/stores/monroe-mobile-auto-glass", "West Monroe", "700 Stella St"],
    ],
  },
  {
    name: "Maine",
    href: "/locations/state/maine",
    stores: [
      ["/stores/augusta", "Augusta", "251 State St"],
      ["/stores/bangor", "Bangor", "1498 Hammond St"],
      ["/stores/portland", "Portland", "421 Warren Ave"],
      ["/stores/skowhegan-me", "Skowhegan", "10 Somerset Business Pkwy"],
    ],
  },
  {
    name: "Maryland",
    href: "/locations/state/maryland",
    stores: [
      ["/stores/annapolis", "Annapolis", "1950 West St"],
      ["/stores/bethesda", "Bethesda", "7841 Old Georgetown Rd"],
      ["/stores/capitol-heights", "Capitol Heights", "8701 Ritchie Dr"],
      ["/stores/churchville", "Churchville", "2832D Churchville Rd"],
      ["/stores/columbia-md", "Columbia", "9255 Berger Rd"],
      ["/stores/cumberland", "Cumberland", "10218 Mount Savage Rd Nw"],
      ["/stores/frederick", "Frederick", "1 Wormans Mill Ct"],
      ["/stores/glen-burnie", "Glen Burnie", "906 Crain Hwy N"],
      ["/stores/hagerstown", "Hagerstown", "13130 Pennsylvania Ave"],
      ["/stores/prince-frederick", "Prince Frederick", "1650 Solomons Island Rd S"],
      ["/stores/reisterstown", "Reisterstown", "68 Main St"],
      ["/stores/rockville", "Rockville", "273 Derwood Cir"],
      ["/stores/baltimore", "Rosedale", "8985 Yellow Brick Rd"],
      ["/stores/salisbury", "Salisbury", "308 E Carroll St"],
      ["/stores/timonium-md", "Timonium", "200 W Padonia Rd"],
      ["/stores/waldorf", "Waldorf", "2579 Crain Hwy"],
      ["/stores/woodlawn", "Windsor Mill", "2505 Lord Baltimore Dr"],
    ],
  },
  {
    name: "Massachusetts",
    href: "/locations/state/massachusetts",
    stores: [
      ["/stores/acton", "Acton", "65 Great Rd"],
      ["/stores/arlington-ma", "Arlington", "94 Massachusetts Ave"],
      ["/stores/attleboro", "Attleboro", "397 Washington St"],
      ["/stores/beverly", "Beverly", "220 Rantoul St"],
      ["/stores/brighton-ma", "Brighton", "119 North Beacon St"],
      ["/stores/brockton-ma", "Brockton", "495 Main Street"],
      ["/stores/brockton", "Brockton", "806 Belmont St"],
      ["/stores/burlington-ma", "Burlington", "116 Cambridge St"],
      ["/stores/chelmsford", "Chelmsford", "94 Drum Hill Rd"],
      ["/stores/chicopee", "Chicopee", "708 Memorial Dr"],
      ["/stores/dorchester", "Dorchester", "614 Gallivan Blvd"],
      ["/stores/taunton", "East Taunton", "250 Revolutionary Dr"],
      ["/stores/everett-ma-revere-beach", "Everett", "1783 Revere Beach Pkwy"],
      ["/stores/falmouth", "Falmouth", "420 Main St"],
      ["/stores/framingham", "Framingham", "1080 Worcester Rd"],
      ["/stores/franklin-ma", "Franklin", "490 W Central St"],
      ["/stores/lunenburg-ma-massachusetts", "Lunenburg", "39 Massachusetts Ave"],
      ["/stores/lynn-ma", "Lynn", "617 Lynnway"],
      ["/stores/marlborough", "Marlborough", "315 Maple St"],
      ["/stores/new-bedford", "New Bedford", "1240 Purchase St"],
      ["/stores/newburyport", "Newburyport", "3 Graf Rd"],
      ["/stores/north-andover", "North Andover", "1000 Osgood St"],
      ["/stores/northampton", "Northampton", "143 King St"],
      ["/stores/norwood", "Norwood", "181 Everett St"],
      ["/stores/peabody", "Peabody", "230 Andover St"],
      ["/stores/pittsfield", "Pittsfield", "799 Tyler St"],
      ["/stores/plymouth", "Plymouth", "55 Samoset St"],
      ["/stores/quincy-ma", "Quincy", "1017 Hancock St"],
      ["/stores/raynham-ma", "Raynham", "2 New State Hwy"],
      ["/stores/south-yarmouth", "South Yarmouth", "40 Whites Path"],
      ["/stores/wakefield", "Wakefield", "345 North Ave"],
      ["/stores/west-newton", "West Newton", "1199 Washington St"],
      ["/stores/west-springfield", "West Springfield", "57 Norman St"],
      ["/stores/weymouth", "Weymouth", "1411 Main St"],
      ["/stores/billerica", "Woburn", "195 Wildwood Ave"],
      ["/stores/worcester-ma", "Worcester", "229 Park Ave"],
      ["/stores/worcester-southbridge", "Worcester", "515 Southbridge St"],
    ],
  },
  {
    name: "Michigan",
    href: "/locations/state/michigan",
    stores: [
      ["/stores/adrian", "Adrian", "1001 E Us Highway 223"],
      ["/stores/ann-arbor", "Ann Arbor", "3451 Washtenaw Ave"],
      ["/stores/auburn-hills", "Auburn Hills", "2100 E Walton Blvd"],
      ["/stores/battle-creek", "Battle Creek", "861 Capital Ave Sw"],
      ["/stores/brighton", "Brighton", "7979 Grand River Ave"],
      ["/stores/cadillac", "Cadillac", "8960 34 Rd"],
      ["/stores/caledonia", "Caledonia", "6748 Patterson Avenue"],
      ["/stores/canton-mi", "Canton", "6196 N Canton Center Rd"],
      ["/stores/clinton-township", "Clinton Township", "36300 S Gratiot Ave"],
      ["/stores/commerce-township", "Commerce Township", "2891 Haggerty Hwy"],
      ["/stores/eastpointe", "Eastpointe", "18254 E 9 Mile Rd"],
      ["/stores/flint-mi", "Flint", "4451 Miller Rd"],
      ["/stores/gaylord", "Gaylord", "1857 S Otsego Ave"],
      ["/stores/grand-ledge", "Grand Ledge", "126 E Jefferson St"],
      ["/stores/grand-rapids", "Grand Rapids", "3682 Plainfield Ave Ne"],
      ["/stores/iron-mountain", "Iron Mountain", "805 W Frank Pipp Dr"],
      ["/stores/ironwood-mobile-auto-glass", "Ironwood", "645 W Cloverland Dr"],
      ["/stores/kalamazoo", "Kalamazoo", "3417 S Westnedge Ave"],
      ["/stores/livonia", "Livonia", "28201 Schoolcraft Rd"],
      ["/stores/macomb-township", "Macomb", "16057 Leone Dr."],
      ["/stores/marquette", "Marquette", "1400 Division St"],
      ["/stores/midland", "Midland", "1609 Commerce Ct"],
      ["/stores/new-baltimore", "New Baltimore", "31285 23 Mile Rd"],
      ["/stores/muskegon-mobile-auto-glass", "Norton Shores", "102 Sinclair Dr"],
      ["/stores/novi-mi", "Novi", "24300 Novi Rd"],
      ["/stores/okemos", "Okemos", "1761 W Grand River Ave"],
      ["/stores/saginaw", "Saginaw", "3056 Kabobel Dr"],
      ["/stores/sault-ste-marie", "Sault Sainte Marie", "2607 Ashmun St"],
      ["/stores/southfield-mi", "Southfield", "24055 W 10 Mile Rd"],
      ["/stores/southgate-eureka", "Southgate", "16046 Eureka Rd"],
      ["/stores/traverse-city", "Traverse City", "803 Woodmere Ave"],
      ["/stores/troy-mi", "Troy", "1700 West Maple Road"],
      ["/stores/waterford-township", "Waterford", "6215 Highland Rd"],
      ["/stores/zeeland", "Zeeland", "11135 Chicago Dr"],
    ],
  },
  {
    name: "Minnesota",
    href: "/locations/state/minnesota",
    stores: [
      ["/stores/apple-valley", "Apple Valley", "14630 Glenda Dr"],
      ["/stores/baxter", "Baxter", "15229 Edgewood Dr"],
      ["/stores/blaine-mn", "Blaine", "12751 Central Ave. Ne"],
      ["/stores/brooklyn-park", "Brooklyn Park", "8086 Brooklyn Blvd"],
      ["/stores/burnsville", "Burnsville", "14051 Grand Ave"],
      ["/stores/crystal-mn", "Crystal", "5530 Lakeland Ave N"],
      ["/stores/duluth-mn", "Duluth", "16 S Arlington Ave"],
      ["/stores/eden-prairie", "Eden Prairie", "8453 Joiner Way"],
      ["/stores/grand-maris-mn", "Grand Marais", "1910 W Highway 61"],
      ["/stores/hibbing-mn", "Hibbing", "515 W 41St St"],
      ["/stores/mankato-mn", "Mankato", "1761 Bassett Dr"],
      ["/stores/maple-grove", "Maple Grove", "13354 Grove Dr"],
      ["/stores/minneapolis", "Minneapolis", "504 Malcolm Ave Se"],
      ["/stores/owatonna", "Owatonna", "490 W North St"],
      ["/stores/park-rapids-mn", "Park Rapids", "1013 1St St E"],
      ["/stores/nw-rochester-mn", "Rochester", "845 38Th St Nw"],
      ["/stores/roseville-mn", "Roseville", "2500 Cleveland Ave N"],
      ["/stores/st-cloud-mn", "Saint Cloud", "1036 33Rd St S"],
      ["/stores/st-paul-maplewood", "Saint Paul", "1715 Highway 36 E"],
      ["/stores/south-st-paul", "South St Paul", "116 Concord Exchange S"],
      ["/stores/waite-park", "Waite Park", "29 6Th Ave S"],
      ["/stores/willmar", "Willmar", "1502 1St St S"],
      ["/stores/winona-mn", "Winona", "1301 Gilmore Ave"],
    ],
  },
  {
    name: "Mississippi",
    href: "/locations/state/mississippi",
    stores: [
      ["/stores/gulfport", "Gulfport", "10333 Corporate Dr"],
      ["/stores/hattiesburg", "Hattiesburg", "6180 U S Highway 98"],
      ["/stores/madison-ms", "Madison", "119A Enterprise Dr"],
      ["/stores/pearl", "Pearl", "1039 Centre Pointe Blvd"],
      ["/stores/southaven", "Southaven", "8425 Airways Blvd"],
    ],
  },
  {
    name: "Missouri",
    href: "/locations/state/missouri",
    stores: [
      ["/stores/columbia-mobile-auto-glass", "Columbia", "809 Vandiver Dr"],
      ["/stores/columbia-mo", "Columbia", "902 Conley Road"],
      ["/stores/independence", "Independence", "13901 E 42Nd Ter S"],
      ["/stores/jefferson-city-mo", "Jefferson City", "607 Dix Road"],
      ["/stores/joplin-mobile-auto-glass", "Joplin", "2010 Roosevelt Ave"],
      ["/stores/kansas-city-gladstone", "Kansas City", "8147 N Oak Trfy"],
      ["/stores/kansas-city", "Kansas City", "1820 N Corrington Ave"],
      ["/stores/lees-summit", "Lees Summit", "801 Se 3Rd St"],
      ["/stores/nixa", "Nixa", "1846 N Commerce Dr"],
      ["/stores/o-fallon", "O Fallon", "1180 W Terra Ln"],
      ["/stores/osage-beach-mo", "Osage Beach", "5360 Osage Beach Parkway"],
      ["/stores/rolla-mobile-auto-glass", "Rolla", "2311 N Bishop Ave"],
      ["/stores/saint-joseph", "Saint Joseph", "1802 Frederick Ave"],
      ["/stores/maryland-heights", "Saint Louis", "2055 Westport Center Dr"],
      ["/stores/sedalia-mo", "Sedalia", "1700 West Broadway Blvd"],
      ["/stores/battlefield-rd", "Springfield", "1607 E Battlefield Rd"],
      ["/stores/st-louis", "St Louis", "11182 S Towne Square"],
    ],
  },
  {
    name: "Montana",
    href: "/locations/state/montana",
    stores: [
      ["/stores/billings", "Billings", "1002 Main St"],
      ["/stores/bozeman", "Bozeman", "200 S 23Rd Ave"],
      ["/stores/great-falls", "Great Falls", "315 10Th Ave S"],
      ["/stores/helena-mobile-auto-glass", "Helena", "1314 Euclid Ave"],
      ["/stores/kalispell-mt", "Kalispell", "1212 E Hwy 2"],
      ["/stores/missoula", "Missoula", "2400 South Ave W"],
    ],
  },
  {
    name: "Nebraska",
    href: "/locations/state/nebraska",
    stores: [
      ["/stores/columbus-ne", "Columbus", "2203 23Rd St"],
      ["/stores/grand-island", "Grand Island", "2124 W 2Nd St"],
      ["/stores/kearney-ne", "Kearney", "3620 2Nd Avenue"],
      ["/stores/lincoln", "Lincoln", "3630 Cornhusker Hwy"],
      ["/stores/north-platte", "North Platte", "809 N Jeffers St"],
      ["/stores/omaha-ne", "Omaha", "4831 N 90Th St"],
      ["/stores/omaha-ralston", "Ralston", "5740 S 77Th St"],
      ["/stores/scottsbluff", "Scottsbluff", "1204 Broadway"],
    ],
  },
  {
    name: "Nevada",
    href: "/locations/state/nevada",
    stores: [
      ["/stores/carson-city", "Carson City", "1770 Dori Way"],
      ["/stores/elko-nv", "Elko", "1955 Pinion Rd"],
      ["/stores/henderson-nv", "Henderson", "1251 American Pacific Dr"],
      ["/stores/las-vegas-sunrise-manor", "Las Vegas", "4601 E Cheyenne Ave"],
      ["/stores/las-vegas-canyon-gate", "Las Vegas", "2055 S Rainbow Blvd"],
      ["/stores/las-vegas-sunset-park", "Las Vegas", "2345 E Sunset Rd"],
      ["/stores/reno", "Reno", "2825 Kietzke Ln"],
    ],
  },
  {
    name: "New Hampshire",
    href: "/locations/state/new-hampshire",
    stores: [
      ["/stores/gorham", "Gorham", "299 Main St"],
      ["/stores/hooksett", "Hooksett", "203 Londonderry Tpke"],
      ["/stores/keene", "Keene", "80 Krif Rd"],
      ["/stores/nashua", "Nashua", "522 Amherst St"],
      ["/stores/portsmouth-nh-lafayette", "Portsmouth", "2700 Lafayette Rd"],
      ["/stores/tilton", "Tilton", "512 W Main St"],
      ["/stores/windham-nh", "Windham", "26 Haverhill Road"],
    ],
  },
  {
    name: "New Jersey",
    href: "/locations/state/new-jersey",
    stores: [
      ["/stores/absecon", "Absecon", "645 S Mill Rd"],
      ["/stores/bayonne", "Bayonne", "170 E 22Nd Street"],
      ["/stores/cherry-hill", "Cherry Hill", "2001 Nj-70"],
      ["/stores/east-brunswick", "East Brunswick", "377 Rt 18 S"],
      ["/stores/freehold", "Freehold", "505 Okerson Road"],
      ["/stores/hackensack-nj", "Hackensack", "516 Main Street"],
      ["/stores/hackettstown", "Hackettstown", "319 Mountain Ave"],
      ["/stores/newton", "Newton", "483 Us Hwy 206 N"],
      ["/stores/parsippany-nj", "Parsippany", "196 Us 46"],
      ["/stores/pine-brook", "Pine Brook", "10 New Maple Ave"],
      ["/stores/toms-river-nj", "Toms River", "1406 Route 37 E."],
      ["/stores/wayne-nj", "Wayne", "2264 Hamburg Tpke"],
      ["/stores/willingboro-nj", "Willingboro", "498 Beverly Rancocas Rd."],
    ],
  },
  {
    name: "New Mexico",
    href: "/locations/state/new-mexico",
    stores: [
      ["/stores/albuquerque-caminito-coors", "Albuquerque", "6644 Caminito Coors Nw"],
      ["/stores/gallup-mobile-auto-glass", "Albuquerque", "8300 C Jefferson Ne"],
      ["/stores/albuquerque-nm", "Albuquerque", "1108 Juan Tabo Ne"],
      ["/stores/albuquerque", "Albuquerque", "8300 Jefferson St Ne"],
      ["/stores/carlsbad-nm-buckner", "Carlsbad", "1801-2 Mission Ave"],
      ["/stores/clovis-nm", "Clovis", "509 Playa Drive Unit 1621 & 1622"],
      ["/stores/farmington", "Farmington", "1795 E 20Th St"],
      ["/stores/las-cruces-mobile-auto-glass", "Mesilla Park", "3317 S Main St"],
      ["/stores/santa-fe-mobile-auto-glass", "Santa Fe", "41 Bisbee Ct"],
    ],
  },
  {
    name: "New York",
    href: "/locations/state/new-york",
    stores: [
      ["/stores/albany", "Albany", "1845 Central Ave"],
      ["/stores/bay-shore", "Bay Shore", "1782 Union Blvd"],
      ["/stores/bridgehampton", "Bridgehampton", "2155 Montauk Hwy # 752"],
      ["/stores/bronx", "Bronx", "1108 Zerega Avenue"],
      ["/stores/brooklyn", "Brooklyn", "8672 18Th Ave"],
      ["/stores/buffalo", "Buffalo", "1672 Clinton Street"],
      ["/stores/monroe", "Chester", "1137 State Route 17M"],
      ["/stores/clarence-ny", "Clarence", "8916 Sheridan Dr"],
      ["/stores/depew", "Depew", "2918 Walden Ave"],
      ["/stores/east-syracuse", "East Syracuse", "7265 Northern Blvd"],
      ["/stores/farmingdale-ny", "Farmingdale", "45 Broadhollow Road"],
      ["/stores/freeport", "Freeport", "210 W Sunrise Hwy"],
      ["/stores/glendale", "Glendale", "7102 Cypress Hills St"],
      ["/stores/great-neck", "Great Neck", "275 E Shore Rd"],
      ["/stores/hamburg", "Hamburg", "4990 Camp Rd"],
      ["/stores/commack", "Hauppauge", "1818 Pacific St"],
      ["/stores/hornell", "Hornell", "7500 Seneca Rd N"],
      ["/stores/huntington-station", "Huntington Station", "1659 New York Ave"],
      ["/stores/ithaca", "Ithaca", "150 Cecil Malone Dr"],
      ["/stores/jamestown-mobile-auto-glass", "Jamestown", "345 Livingston Ave"],
      ["/stores/kingston-ny", "Kingston", "650 Ulster Ave"],
      ["/stores/latham", "Latham", "327 Old Niskayuna Rd."],
      ["/stores/lockport", "Lockport", "6255 S Transit Rd"],
      ["/stores/astoria", "Long Island City", "32-56 49Th Street"],
      ["/stores/massena", "Massena", "11 Railroad St"],
      ["/stores/middletown", "Middletown", "500 N Galleria Dr"],
      ["/stores/monticello", "Monticello", "51 Forestburgh Rd"],
      ["/stores/mount-kisco", "Mount Kisco", "379 N Bedford Rd"],
      ["/stores/nanuet", "Nanuet", "198 E Route 59"],
      ["/stores/oneonta", "Oneonta", "195 Oneida St"],
      ["/stores/patchogue-mobile-auto-glass", "Patchogue", "167 Medford Ave"],
      ["/stores/plattsburgh", "Plattsburgh", "186 Margaret St"],
      ["/stores/poughkeepsie", "Poughkeepsie", "2535 South Road"],
      ["/stores/queensbury", "Queensbury", "20 Main St"],
      ["/stores/riverhead", "Riverhead", "222 W Main St"],
      ["/stores/rochester-ny", "Rochester", "736 East Ridge Road"],
      ["/stores/rochester-jefferson", "Rochester", "900 Jefferson Rd"],
      ["/stores/rochester", "Rochester", "1260 Scottsville Rd"],
      ["/stores/st-james", "Saint James", "799 Middle Country Rd"],
      ["/stores/syracuse", "Syracuse", "3528 W Genesee St"],
      ["/stores/vestal", "Vestal", "313 Vestal Pkwy E"],
      ["/stores/walworth-ny", "Walworth", "2140 Walworth-Penfield Rd"],
      ["/stores/wappinger-falls", "Wappingers Falls", "110 Airport Dr"],
      ["/stores/watertown-ny", "Watertown", "18929 Us Route 11"],
      ["/stores/westbury", "Westbury", "730 Old Country Rd"],
      ["/stores/white-plains", "White Plains", "102 S Kensico Ave"],
      ["/stores/yorkville", "Yorkville", "701 Oriskany Blvd"],
    ],
  },
  {
    name: "North Carolina",
    href: "/locations/state/north-carolina",
    stores: [
      ["/stores/morrisville-nc", "Apex", "2203 Energy Dr"],
      ["/stores/asheville-nc", "Asheville", "6 Westside Drive"],
      ["/stores/asheville", "Asheville", "1226 Hendersonville Rd"],
      ["/stores/burlington-nc", "Burlington", "1424 N Church St"],
      ["/stores/charlotte", "Charlotte", "1301 Carrier Dr"],
      ["/stores/charlotte-nc", "Charlotte", "5029 West W.T. Harris Blvd"],
      ["/stores/concord-nc", "Concord", "1000 Branchview Dr Ne"],
      ["/stores/lincolnton-mobile-auto-glass", "Durham", "3602 Durham Chapel Hill"],
      ["/stores/fayetteville-nc", "Fayetteville", "3730 Ramsey St"],
      ["/stores/gastonia-mobile-auto-glass", "Gastonia", "101 W Franklin Blvd"],
      ["/stores/greenville-nc", "Greenville", "115 Sw Greenville Blvd"],
      ["/stores/hickory", "Hickory", "1961 Us Highway 70 Se"],
      ["/stores/jacksonville-mobile-auto-glass", "Jacksonville", "115 Atlas Brown Dr"],
      ["/stores/jamestown-nc", "Jamestown", "4845 West Wendover Ave"],
      ["/stores/mt-airy-mobile-auto-glass", "Mount Airy", "1005 W Lebanon St"],
      ["/stores/new-bern-nc", "New Bern", "1810 Old Airport Rd"],
      ["/stores/pineville-nc", "Pineville", "10822 Pineville Road Unit C"],
      ["/stores/raleigh", "Raleigh", "3070 Business Park Dr"],
      ["/stores/raleigh-nc", "Raleigh", "6550 Meridien Drive"],
      ["/stores/roanoke-rapids-nc", "Roanoke Rapids", "900 Julian R Allsbrook Hwy"],
      ["/stores/rocky-mount-nc", "Rocky Mount", "2754 N Wesleyan Blvd"],
      ["/stores/wilmington-nc", "Wilmington", "8740 Market St"],
      ["/stores/winston-salem", "Winston Salem", "2743 Peters Creek Pkwy"],
    ],
  },
  {
    name: "North Dakota",
    href: "/locations/state/north-dakota",
    stores: [
      ["/stores/bismarck-nd", "Bismarck", "2045 71St Ave Ne"],
      ["/stores/fargo", "Fargo", "210 42Nd St S"],
      ["/stores/minot", "Minot", "405 28Th Ave Sw"],
    ],
  },
  {
    name: "Ohio",
    href: "/locations/state/ohio",
    stores: [
      ["/stores/akron", "Akron", "2567 S Arlington Rd"],
      ["/stores/avon", "Avon", "1049 Rt 83"],
      ["/stores/strongsville-oh-southpark-central", "Brunswick", "1402 Pearl Rd"],
      ["/stores/cincinnati", "Cincinnati", "6596 Glenway Ave"],
      ["/stores/cincinnati-oh-gleneste-withamsville", "Cincinnati", "4464 Gleneste-Withamsvil"],
      ["/stores/columbus-oh", "Columbus", "6826 Sawmill Rd"],
      ["/stores/dayton", "Dayton", "8333 Yankee St"],
      ["/stores/dayton-oh", "Dayton", "5719 Brandt Pike"],
      ["/stores/findlay-mobile-auto-glass", "Findlay", "1970 Tiffin Ave"],
      ["/stores/amherst-mobile-auto-glass", "Huron", "2401 Sawmill Pkwy"],
      ["/stores/lewis-center-oh", "Lewis Center", "1343 Cameron Ave"],
      ["/stores/mansfield-mobile-auto-glass", "Mansfield", "1139 Park Ave W"],
      ["/stores/mentor-oh-tyler", "Mentor", "7408 Tyler Blvd"],
      ["/stores/dover-mobile-auto-glass", "New Philadelphia", "1309-A Monroe Street Nw"],
      ["/stores/st-clairsville", "Saint Clairsville", "50704 National Rd"],
      ["/stores/steubenville", "Steubenville", "636 Adams St"],
      ["/stores/toledo", "Toledo", "503 S Reynolds Rd"],
      ["/stores/grove-city-oh", "Urbancrest", "3455 Centerpoint Dr"],
      ["/stores/cleveland-valley-view", "Valley View", "6050 Towpath Dr"],
      ["/stores/warren", "Warren", "2914 Elm Rd Ne"],
      ["/stores/west-chester-oh", "West Chester", "5900 Muhlhauser Rd"],
      ["/stores/zanesville-oh", "Zanesville", "3350 Maple Ave."],
    ],
  },
  {
    name: "Oklahoma",
    href: "/locations/state/oklahoma",
    stores: [
      ["/stores/ardmore-ok", "Ardmore", "1900 Veterans Blvd"],
      ["/stores/bartlesville", "Bartlesville", "5300 Nowata Rd"],
      ["/stores/tulsa-broken-arrow", "Broken Arrow", "3825 W Albany St"],
      ["/stores/elk-city-ok", "Elk City", "1224 South Eastern Ave Unit C16"],
      ["/stores/enid", "Enid", "117 N Van Buren St"],
      ["/stores/lawton-ok", "Lawton", "2302 Sw Lee Blvd"],
      ["/stores/oklahoma-city", "Oklahoma City", "900 Metropolitan Ave"],
      ["/stores/oklahoma-city-ok", "Oklahoma City", "601 E Memorial Road"],
      ["/stores/oklahoma-city-s-western", "Oklahoma City", "12025 S Western Ave"],
      ["/stores/ponca-city", "Ponca City", "1801 E Hartford Ave"],
    ],
  },
  {
    name: "Oregon",
    href: "/locations/state/oregon",
    stores: [
      ["/stores/albany-or", "Albany", "245 Queen Ave Se"],
      ["/stores/beaverton", "Beaverton", "13227 Sw Canyon Rd"],
      ["/stores/beaverton-or", "Beaverton", "7893 Sw Cirrus Dr"],
      ["/stores/bend-or-", "Bend", "61562 American Loop"],
      ["/stores/coos-bay-or", "Coos Bay", "1503 Ocean Blvd Nw"],
      ["/stores/eugene", "Eugene", "784 S Bertelsen Rd"],
      ["/stores/keizer", "Keizer", "4229 River Rd N"],
      ["/stores/klamath-falls-or", "Klamath Falls", "2960 Maywood Dr"],
      ["/stores/medford-or", "Medford", "683 Brian Way"],
      ["/stores/ontario-or", "Ontario", "1196 Se 2Nd St"],
      ["/stores/portland-or", "Portland", "6841 Ne Columbia Blvd"],
      ["/stores/redmond-or", "Redmond", "4626 Sw 21St St"],
      ["/stores/tualatin-or", "Tualatin", "9606 Sw Tualatin-Sherwood Rd"],
      ["/stores/warrenton-or", "Warrenton", "51 Ne Harbour Court"],
    ],
  },
  {
    name: "Pennsylvania",
    href: "/locations/state/pennsylvania",
    stores: [
      ["/stores/beaver-falls", "Beaver Falls", "2400 9Th Ave"],
      ["/stores/bedford", "Bedford", "7722 Lincoln Hwy"],
      ["/stores/bloomsburg", "Bloomsburg", "3081 Columbia Blvd"],
      ["/stores/bradford", "Bradford", "570 Chestnut Street Ext"],
      ["/stores/bridgeport-pa", "Bridgeport", "25 West 4Th Street"],
      ["/stores/bridgeville", "Bridgeville", "690 Bower Hill Rd"],
      ["/stores/butler", "Butler", "180 Pittsburgh Rd"],
      ["/stores/carlisle", "Carlisle", "1780 W Trindle Rd"],
      ["/stores/chambersburg", "Chambersburg", "1380 Lincoln Way E"],
      ["/stores/dubois", "Du Bois", "2722 Oklahoma Salem Rd"],
      ["/stores/duncansville", "Duncansville", "2240 Plank Rd"],
      ["/stores/ephrata", "Ephrata", "1644 W Main St"],
      ["/stores/erie-pa-12th", "Erie", "2166-2170 W. 12Th Street"],
      ["/stores/fairless-hills", "Fairless Hills", "131 Lincoln Hwy"],
      ["/stores/franklin", "Franklin", "1050 Liberty St"],
      ["/stores/greensburg", "Greensburg", "123 Donohoe Rd"],
      ["/stores/hanover", "Hanover", "130 Eisenhower Dr"],
      ["/stores/harrisburg", "Harrisburg", "1251 Eisenhower Blvd"],
      ["/stores/hazleton", "Hazle Township", "533 Can-Do Expy"],
      ["/stores/hermitage", "Hermitage", "1430 N Hermitage Rd"],
      ["/stores/johnstown", "Johnstown", "99 Roosevelt Blvd"],
      ["/stores/kingston", "Kingston", "355 Pierce St"],
      ["/stores/lancaster", "Lancaster", "1761 Columbia Ave"],
      ["/stores/lebanon", "Lebanon", "1500 Cumberland St"],
      ["/stores/meadville", "Meadville", "19310 Cochranton Rd"],
      ["/stores/mechanicsburg", "Mechanicsburg", "5016 Carlisle Pike"],
      ["/stores/south-philadelphia", "Philadelphia", "709 Washington Ave"],
      ["/stores/pittsburgh", "Pittsburgh", "2847 Saw Mill Run Blvd"],
      ["/stores/pittsburgh-frankstown", "Pittsburgh", "10914 Frankstown Rd"],
      ["/stores/pittston", "Pittston", "175 Centerpoint Blvd"],
      ["/stores/reading", "Reading", "3101 Centre Ave"],
      ["/stores/dickson-city-pa", "Scranton", "640 Scranton Carbondale"],
      ["/stores/selinsgrove", "Selinsgrove", "1885 N Susquehanna Trl"],
      ["/stores/sewickley", "Sewickley", "205 Overlook Drive"],
      ["/stores/smock", "Smock", "1010 Franklin Dr"],
      ["/stores/springfield", "Springfield", "210 Baltimore Pike"],
      ["/stores/state-college", "State College", "2218 N Atherton St"],
      ["/stores/stroudsburg", "Stroudsburg", "205 Applegate Rd"],
      ["/stores/washington", "Washington", "859 Jefferson Ave"],
      ["/stores/wellsboro", "Wellsboro", "11480 Route 6"],
      ["/stores/west-chester", "West Chester", "619 E Gay St"],
      ["/stores/whitehall", "Whitehall", "2518 Macarthur Rd"],
      ["/stores/williamsport", "Williamsport", "482 E 3Rd St"],
      ["/stores/willow-grove-pa", "Willow Grove", "2550 West Moreland Rd."],
      ["/stores/york", "York", "192 Memory Ln"],
    ],
  },
  {
    name: "Rhode Island",
    href: "/locations/state/rhode-island",
    stores: [
      ["/stores/johnston-ri", "Johnston", "175 Putnam Pike"],
      ["/stores/warwick", "Warwick", "100 Bay State Ave"],
    ],
  },
  {
    name: "South Carolina",
    href: "/locations/state/south-carolina",
    stores: [
      ["/stores/anderson-sc-mobile-auto-glass", "Anderson", "4482 Liberty Hwy"],
      ["/stores/bluffton-sc", "Bluffton", "266 Red Cedar St"],
      ["/stores/camden", "Camden", "628 W Dekalb St"],
      ["/stores/columbia", "Columbia", "161 Winhill Rd"],
      ["/stores/florence-sc", "Florence", "2608 W Palmetto St"],
      ["/stores/georgetown-sc", "Georgetown", "2302 Highmarket St"],
      ["/stores/greenville-sc", "Greenville", "128 Transit Drive"],
      ["/stores/greenville", "Greenville", "201 Forrester Dr"],
      ["/stores/little-river", "Little River", "4370 Sea Mountain Hwy"],
      ["/stores/manning", "Manning", "200 Commerce St"],
      ["/stores/mount-pleasant-sc", "Mount Pleasant", "1407 Stuart Engals Blvd"],
      ["/stores/myrtle-beach", "Myrtle Beach", "4900 Hwy 17 Bypass South"],
      ["/stores/charleston", "N Charleston", "7651 Palmetto Commerce Pk"],
      ["/stores/north-augusta", "North Augusta", "424 Edgefield Rd"],
      ["/stores/north-charleston-sc", "North Charleston", "4975 Dorchester Rd"],
      ["/stores/orangeburg-sc", "Orangeburg", "2015 Saint Matthews Rd"],
      ["/stores/rock-hill", "Rock Hill", "710 W Main St"],
      ["/stores/roebuck", "Roebuck", "590 Southport Rd"],
      ["/stores/summerville-college-park", "Summerville", "1341 College Park Rd"],
      ["/stores/sumter", "Sumter", "725 N Pike W"],
      ["/stores/taylors-sc", "Taylors", "3551 Rutherford Road"],
      ["/stores/walterboro", "Walterboro", "744 Bells Hwy"],
    ],
  },
  {
    name: "South Dakota",
    href: "/locations/state/south-dakota",
    stores: [
      ["/stores/brookings-sd", "Brookings", "200 Prince Dr"],
      ["/stores/rapid-city", "Rapid City", "1141 Deadwood Ave"],
      ["/stores/sioux-falls", "Sioux Falls", "129 N Minnesota Ave"],
    ],
  },
  {
    name: "Tennessee",
    href: "/locations/state/tennessee",
    stores: [
      ["/stores/bristol", "Bristol", "1815 Volunteer Pkwy"],
      ["/stores/chattanooga", "Chattanooga", "4823 Bonny Oaks Dr"],
      ["/stores/clarksville-tn", "Clarksville", "1765 Alpine Drive"],
      ["/stores/cookeville-tn-", "Cookeville", "5080 Academy Road"],
      ["/stores/jackson-tn", "Jackson", "4355 Highway 45 N"],
      ["/stores/johnson-city-tn", "Johnson City", "3400 Timberlake Rd"],
      ["/stores/knoxville-tn-western", "Knoxville", "5705 Western Ave"],
      ["/stores/knoxville-tn", "Knoxville", "411 Lovell Rd"],
      ["/stores/knoxville", "Knoxville", "11235 Threadstone Ln"],
      ["/stores/memphis", "Memphis", "6543 Winchester Rd"],
      ["/stores/memphis-covington-pike", "Memphis", "2439 B Convington Pike"],
      ["/stores/morristown-tn", "Morristown", "104 S Sugar Hollow Rd"],
      ["/stores/murfreesboro-mobile-auto-glass", "Murfreesboro", "1232 Salem Park Ct"],
      ["/stores/nashville", "Nashville", "815 Cowan St"],
      ["/stores/brentwood-mobile-auto-glass", "Paris", "179 Guthrie Road"],
    ],
  },
  {
    name: "Texas",
    href: "/locations/state/texas",
    stores: [
      ["/stores/abilene", "Abilene", "4220 N 1St St"],
      ["/stores/amarillo", "Amarillo", "4227 S Western St"],
      ["/stores/andrews-tx", "Andrews", "602 W Broadway St"],
      ["/stores/arlington-tx-cooper", "Arlington", "2411 S Cooper St"],
      ["/stores/austin-tx-kramer", "Austin", "1826 Kramer Ln"],
      ["/stores/austin-tx", "Austin", "16602 N. Ih 35"],
      ["/stores/austin-frontage", "Austin", "5717 S Ih 35 Frontage Rd"],
      ["/stores/austin", "Austin", "710 W Howard Ln"],
      ["/stores/baytown", "Baytown", "4110 Decker Dr"],
      ["/stores/beaumont", "Beaumont", "3610 Stagg Dr"],
      ["/stores/brownsville", "Brownsville", "4001 N Expressway"],
      ["/stores/bryan", "Bryan", "3818 South College Avenue"],
      ["/stores/burnet-tx", "Burnet", "1100 Buchanan Dr"],
      ["/stores/cedar-hill-tx", "Cedar Hill", "408 North Clark Road"],
      ["/stores/columbus-tx", "Columbus", "1223 Walnut St Ste A"],
      ["/stores/corpus-christi-tx", "Corpus Christi", "5717 South Padre Island Drive"],
      ["/stores/dalls-inwood", "Dallas", "2880 Inwood Road"],
      ["/stores/deer-park-tx", "Deer Park", "4840 Center St"],
      ["/stores/denton-tx", "Denton", "3330 E University Dr"],
      ["/stores/el-paso", "El Paso", "3815 Buckner St"],
      ["/stores/fort-stockton-tx", "Fort Stockton", "705 W Dickinson Blvd"],
      ["/stores/fort-worth-tx", "Fort Worth", "8200 South Freeway"],
      ["/stores/fort-worth-tx-northern-cross", "Fort Worth", "2751 Northern Cross Blvd"],
      ["/stores/frisco-tx", "Frisco", "6065 Sports Village Rd"],
      ["/stores/greenville-tx", "Greenville", "7907 Traders Cir"],
      ["/stores/houston-tx", "Houston", "1818 Bingle Road"],
      ["/stores/willowbrook-tx", "Houston", "12723 Cutten Rd"],
      ["/stores/humble", "Humble", "20465 Us 59"],
      ["/stores/katy", "Katy", "24025 Katy Fwy"],
      ["/stores/temple-mobile-auto-glass", "Killeen", "2102 W Stan Schluter Loop"],
      ["/stores/leander", "Leander", "3651 N Us Highway 183"],
      ["/stores/lewisville", "Lewisville", "2129 S Stemmons Fwy"],
      ["/stores/san-antonio-tx", "Live Oak", "13943 Toepperwein Rd"],
      ["/stores/lubbock2", "Lubbock", "5103 S Loop 289"],
      ["/stores/lufkin-tx", "Lufkin", "2001 N John Redditt Dr"],
      ["/stores/mcallen", "Mcallen", "3620 N 23Rd St"],
      ["/stores/mckinney-tx", "Mckinney", "417 Power House St."],
      ["/stores/mesquite", "Mesquite", "2131 N Town East Blvd"],
      ["/stores/midland-texas", "Midland", "12322 State Highway 191"],
      ["/stores/north-richland--hills", "N Richland Hills", "5649 Rufe Snow Dr"],
      ["/stores/odessa-penwell-ave", "Odessa", "400 Penwell Ave"],
      ["/stores/pearland-tx", "Pearland", "2633 Miller Ranch Road"],
      ["/stores/dallas", "Plano", "1601 E Plano Pkwy"],
      ["/stores/richmond-tx", "Richmond", "21809 Beechnut Road"],
      ["/stores/rosenberg", "Rosenberg", "27970 Southwest Fwy"],
      ["/stores/san-angelo", "San Angelo", "300 W Beauregard Ave"],
      ["/stores/san-antonio-balcones", "San Antonio", "6531 Nw Loop 410"],
      ["/stores/san-antonio-silicon", "San Antonio", "12914 Silicon Dr"],
      ["/stores/san-marcos-tx-", "San Marcos", "2061 Clovis Barker Rd"],
      ["/stores/shenandoah", "Shenandoah", "19285 David Memorial Dr"],
      ["/stores/texarkana", "Texarkana", "3400 Summerhill Rd"],
      ["/stores/tyler", "Tyler", "4043 S Broadway Ave"],
      ["/stores/victoria", "Victoria", "3201 E Red River St"],
      ["/stores/waco-tx", "Waco", "4301 Franklin Avenue"],
      ["/stores/weatherford-tx", "Weatherford", "1902 Fort Worth Highway"],
      ["/stores/webster", "Webster", "123 W Nasa Pkwy"],
      ["/stores/wichita-falls-mobile-auto-glass", "Wichita Falls", "4111 Old Jacksboro Hwy"],
    ],
  },
  {
    name: "Utah",
    href: "/locations/state/utah",
    stores: [
      ["/stores/american-fork", "American Fork", "752 E State Rd"],
      ["/stores/bountiful", "Bountiful", "530 S 500 W"],
      ["/stores/brigham-ut", "Brigham City", "835 S Main St"],
      ["/stores/draper", "Draper", "417 E 12300 S"],
      ["/stores/holladay", "Holladay", "1851 E Murray Holladay Rd"],
      ["/stores/layton", "Layton", "1357 N Main St"],
      ["/stores/logan", "Logan", "905 N Main St"],
      ["/stores/orem", "Orem", "1207 W 800 N"],
      ["/stores/park-city-ut", "Park City", "3872 North Old Highway 40"],
      ["/stores/provo", "Provo", "443 W 100 N"],
      ["/stores/riverdale-ut", "Riverdale", "760 W River Park Dr"],
      ["/stores/salt-lake-city-w", "Salt Lake City", "280 W 500 S"],
      ["/stores/salt-lake-city", "Salt Lake City", "1834 S 4650 W"],
      ["/stores/salt-lake-city-south", "Salt Lake City", "2390 S State St"],
      ["/stores/sandy", "Sandy", "83 E 11400 S"],
      ["/stores/sandy-utah", "Sandy", "460 W 9000 S"],
      ["/stores/spanish-fork-mobile-auto-glass", "Spanish Fork", "238 E 1000 N"],
      ["/stores/st-george", "St George", "528 N Mall Dr"],
      ["/stores/taylorsville", "Taylorsville", "3564 W 6200 S"],
      ["/stores/tooele-mobile-auto-glass", "Tooele", "1521 N Main St"],
      ["/stores/vernal", "Vernal", "962 E Main St"],
    ],
  },
  {
    name: "Vermont",
    href: "/locations/state/vermont",
    stores: [
      ["/stores/barre", "Barre", "1246 Us Route 302"],
      ["/stores/newport", "Newport", "593 Union St"],
      ["/stores/rutland", "Rutland", "134 Strongs Ave"],
      ["/stores/st-albans", "Saint Albans", "284 N Main St"],
      ["/stores/st-johnsbury", "St Johnsbury", "371 Memorial Dr"],
      ["/stores/white-river-junction", "White River Junction", "669 N Main St"],
      ["/stores/williston2", "Williston", "21 Adams Dr."],
    ],
  },
  {
    name: "Virginia",
    href: "/locations/state/virginia",
    stores: [
      ["/stores/alexandria-quaker", "Alexandria", "10 S Quaker Ln"],
      ["/stores/arlington", "Arlington", "4332 Washington Blvd"],
      ["/stores/charlottesville", "Charlottesville", "1907 Seminole Trail"],
      ["/stores/chesapeake", "Chesapeake", "1545 Crossways Blvd.Ste.M"],
      ["/stores/danville", "Danville", "3000 Riverside Dr"],
      ["/stores/fairfax", "Fairfax", "2800 Dorr Ave"],
      ["/stores/forest", "Forest", "17824 Forest Rd"],
      ["/stores/fredericksburg-va", "Fredericksburg", "4827 Plank Road"],
      ["/stores/hampton", "Hampton", "2121 W Mercury Blvd"],
      ["/stores/manassas", "Manassas", "9412 Grant Ave"],
      ["/stores/midlothian", "Midlothian", "11251 Hull Street Rd"],
      ["/stores/richmond", "Richmond", "3201 Rosedale Ave"],
      ["/stores/roanoke", "Roanoke", "4528 Williamson Rd Sw"],
      ["/stores/harrisonburg-va-early", "Rockingham", "4809 South Valley Pike"],
      ["/stores/sterling", "Sterling", "23035 Douglas Ct"],
      ["/stores/virginia-beach-va", "Virginia Beach", "2814 Virginia Beach Blvd"],
      ["/stores/williamsburg", "Williamsburg", "2215 Richmond Rd"],
      ["/stores/winchester", "Winchester", "238 Airport Rd"],
      ["/stores/woodbridge", "Woodbridge", "2726 Metro Plz"],
    ],
  },
  {
    name: "Washington",
    href: "/locations/state/washington",
    stores: [
      ["/stores/auburn", "Auburn", "420 37Th St Nw"],
      ["/stores/bellevue", "Bellevue", "12730 Bel Red Rd"],
      ["/stores/burlington", "Bellingham", "4010 Meridian St"],
      ["/stores/bellingham-wa", "Bellingham", "1512 N State St"],
      ["/stores/bremerton-wa", "Bremerton", "555 Bruenn Ave"],
      ["/stores/everett", "Everett", "2006 Everett Ave"],
      ["/stores/everett-wa", "Everett", "717 128Th Sw"],
      ["/stores/fife-wa-", "Fife", "3151 20Th St E"],
      ["/stores/kennewick", "Kennewick", "6713 W Clearwater Ste A&B"],
      ["/stores/olympia-wa", "Lacey", "7930 Martin Way E"],
      ["/stores/longview-wa", "Longview", "1554 3Rd Ave"],
      ["/stores/lynden-wa", "Lynden", "407 19Th St"],
      ["/stores/moses-lake-mobile", "Moses Lake", "1096 Rd L. 4 Se"],
      ["/stores/mount-vernon-wa", "Mount Vernon", "1721 E College Way"],
      ["/stores/olympia-comar-wa", "Olympia", "2415 Capital Mall Dr Sw"],
      ["/stores/puyallup", "Puyallup", "938 Valley Ave Nw"],
      ["/stores/puyallup-wa", "Puyallup", "430 N Meridian"],
      ["/stores/seattle-wa-king", "Seattle", "6321 7Th Ave S"],
      ["/stores/sequim", "Sequim", "391 W Washington St"],
      ["/stores/silverdale", "Silverdale", "10726 Silverdale Way Nw"],
      ["/stores/spokane-division-wa", "Spokane", "7777 N Divison St"],
      ["/stores/spokane-wa", "Spokane Valley", "16311 E Euclid Ave"],
      ["/stores/tacoma", "Tacoma", "6426 South Tacoma Way"],
      ["/stores/tacoma-wa", "Tacoma", "2609 S Tacoma Way"],
      ["/stores/tukwila-wa", "Tukwila", "12600 Interurban Ave S"],
      ["/stores/vancouver-wa", "Vancouver", "13412 Ne Fourth Plain Blvd"],
      ["/stores/wenatchee-mobile-auto-glass", "Wenatchee", "1202 Mckittrick St"],
      ["/stores/yakima", "Yakima", "1602 W Lincoln Ave"],
    ],
  },
  {
    name: "West Virginia",
    href: "/locations/state/west-virginia",
    stores: [
      ["/stores/beckley", "Beckley", "100 Plaza Dr"],
      ["/stores/bluefield", "Bluefield", "4200 Big Laurel Hwy"],
      ["/stores/bridgeport-wv-meadowbrook", "Bridgeport", "16 Chenoweth Drive"],
      ["/stores/huntington-barboursville", "Charleston", "124 Lakeview Dr"],
      ["/stores/barboursville", "Huntington", "2512 5Th Ave"],
      ["/stores/morgantown", "Morgantown", "173 Greenbag Rd"],
      ["/stores/parkersburg", "Parkersburg", "900 7Th St"],
    ],
  },
  {
    name: "Wisconsin",
    href: "/locations/state/wisconsin",
    stores: [
      ["/stores/appleton", "Appleton", "1619 W Wisconsin Ave"],
      ["/stores/baraboo-mobile-auto-glass", "Baraboo", "505 South Blvd"],
      ["/stores/eau-claire", "Eau Claire", "2915 N Clairemont Ave"],
      ["/stores/fond-du-lac", "Fond Du Lac", "550 N Main St"],
      ["/stores/green-bay", "Green Bay", "974 Parkview Rd"],
      ["/stores/hudson", "Hudson", "1501 Coulee Rd"],
      ["/stores/janesville", "Janesville", "1612 Holiday Dr"],
      ["/stores/kenosha", "Kenosha", "6010 75Th St"],
      ["/stores/la-crosse", "La Crosse", "615 4Th St S"],
      ["/stores/madison", "Madison", "302 W Beltline Hwy"],
      ["/stores/peshtigo", "Peshtigo", "831 Ogden Rd"],
      ["/stores/rhinelander", "Rhinelander", "1823 N Stevens St"],
      ["/stores/rice-lake", "Rice Lake", "308 W Knapp St"],
      ["/stores/schofield", "Schofield", "6101 Bus Hwy 51 South"],
      ["/stores/pewaukee", "Waukesha", "W238n1600 Busse Rd"],
      ["/stores/milwaukee-west-allis", "West Allis", "10708 W Orchard St"],
      ["/stores/west-bend", "West Bend", "3016 W Washington St"],
      ["/stores/wisconsin-rapids", "Wisconsin Rapids", "831 Sweat Ave"],
    ],
  },
  {
    name: "Wyoming",
    href: "/locations/state/wyoming",
    stores: [
      ["/stores/casper-wy", "Casper", "131 Casper View Ct"],
      ["/stores/cheyenne", "Cheyenne", "501 W Lincolnway"],
      ["/stores/jackson-wy", "Jackson", "1640 Martin Ln"],
    ],
  },
];
